appnexus/lucid

- src/util/child-component.js
There was a bug that was caused by not filtering out `null` values in the old version of `getAllAsProps`, this was fixed by `.filter(x => x)`
> Refactor child-component.js and fix bug

- package.json
- src/docs/index.jsx
react-router 2.0 uses browserHistory 
https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md
addresses #58
> use reaact-router 2.0 browserHistory

- src/docs/index.jsx
- src/docs/index.less
make sidebar scrollable and example names excludes leading numbers to establish render order.
addresses #60
> Docs: sidebar scrollable and example names ignore numbers

- src/index.js
- src/util/generic-tests.jsx
Use named exports only no more default object.
Two reasons for this:
1. ES2015 consumers can use `import * as lucid from 'lucid-ui'` to get the same default object
2. older, non ES2015 consumers will see no difference in their usage: `var lucid = require('lucid-ui');`
> expose lucid utils to consumers and clean exports

- src/util/dom-helpers.js
> #122: use window.pageYOffset instead of window.scrollY for compat.

- src/components/Button/Button.less
------
* Change height from 19px to 20px on small and short buttons
* Added new disabled selector to fix display issue after reset.css added
> #109 Change height from 19px to #20

- src/components/Button/Button.less
- src/components/Expander/Expander.jsx
- src/components/Expander/Expander.less
- src/components/Expander/Expander.reducers.js
- src/components/Expander/Expander.spec.jsx
- src/components/Expander/examples/1.default.jsx
- src/components/Expander/examples/2.expanded.jsx
- src/components/Expander/examples/3.interactive-with-changing-labels.jsx
- src/components/Expander/examples/4.interactive-without-changing-labels.jsx
- src/components/Icon/ChevronIcon/ChevronIcon.jsx
- src/components/Icon/ChevronIcon/ChevronIcon.less
- src/components/Icon/ChevronIcon/ChevronIcon.spec.jsx
- src/components/Icon/ChevronIcon/examples/default.jsx
- src/components/Icon/ResizeIcon/ResizeIcon.jsx
- src/components/LabeledSwitch/LabeledSwitch.jsx
- src/components/LabeledSwitch/LabeledSwitch.less
- src/components/LabeledSwitch/LabeledSwitch.spec.jsx
- src/components/LabeledSwitch/examples/interactive-default.jsx
- src/index.js
- src/styles/components.less
Docspot demo: http://docspot.devnxs.net/projects/lucid/feature-ANXR-190-expand-collapse/#/components/Expander
> Added ChevronIcon and Expander components.

- src/docs/index.jsx
> Update to use lucid table on docs page

- src/components/Autocomplete/Autocomplete.less
- src/components/Autocomplete/examples/1.basic.jsx
We needed `white-space: pre` instead of `white-space: no-wrap` on the suggestion matches to maintain white space correctly.
> Fixes #172 white space in autocomplete

- src/components/Table/Table.jsx
- src/components/Table/Table.spec.jsx
Remove one-off SortedThContent component and clean tests to only use shallow rendering.
> Table cleanup

- package.json
- src/index.js
- src/util/redux.js
- src/util/redux.spec.js
re-targeted https://github.com/appnexus/lucid/pull/198
~~[x] Chrome~~
~~[ ] Firefox~~
~~[ ] Safari~~
~~[ ] IE11 (Win 7)~~
~~[ ] Edge (Win 10)~~
~~[ ] One core team UX approval~~ n/a
+ utility functions for getting react-redux primitives from lucid
reducers/selectors:
+ reducer
+ connectors (mapStateToProps, mapDispatchToProps, mergeProps)
> Redux binding utils

- src/components/ContextMenu/ContextMenu.jsx
> don't render when portal isn't rendered

- src/components/Table/Table.jsx
Just a tiny code update for an inconsistency i noticed.
- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~
> Clean up the passThrough props for Table elements.

- src/components/Table/Table.less
> #283 - fix typo in table-Th-align-right

- src/components/Button/Button.less
There was a missing commit on the previous PR for this issue. This one should clear it up.
> Fixes #292 Button font and FF style issue

- package.json
- src/components/Axis/Axis.spec.js
- src/components/Axis/examples/2.bottom.jsx
- src/components/Axis/examples/3.top.jsx
- src/components/Axis/examples/4.left.jsx
- src/components/Axis/examples/5.right.jsx
- src/components/Axis/examples/6.time.jsx
- src/components/Axis/examples/7.ordinal.jsx
- src/components/BarChart/BarChart.jsx
- src/components/Bars/Bars.jsx
- src/components/Bars/Bars.spec.js
- src/components/Bars/examples/basic.jsx
- src/components/LineChart/LineChart.jsx
- src/components/Lines/Lines.jsx
- src/components/Lines/Lines.spec.js
- src/components/Lines/examples/stacked.jsx
- src/components/Points/Points.jsx
- src/components/Points/Points.spec.js
- src/components/Points/examples/basic.jsx
- src/util/chart-helpers.js
fixes #320 
- #321 `patch`: fixed a critical breaking change introduced by various downstream d3 libraries
> Fix D3 imports

- src/components/Banner/Banner.less
- src/components/Banner/examples/stateless.jsx
fixes #236
- #315 `patch`: fixed bug with `Banner` with small variants and icons
- ~[ ] Unit tests written (`common` at minimum)~
http://docspot.devnxs.net/projects/lucid/236-banner-icon-is-small/#/components/Banner
> fix Banner icon=true isSmall=true styling

- src/components/Button/Button.less
Fixes #316
- #318 `patch`: fixed small issue with white buttons in Safari
> Fix white buttons in Safari

- src/styles/mixins.less
Fixes #244
- #317 `patch`: fixed disabled `Button` styling
> Fix disabled Button styling

- src/components/BarChart/BarChart.jsx
- src/components/BarChart/examples/5.all-the-things.jsx
- src/components/LineChart/LineChart.jsx
- src/components/LineChart/examples/3.dual-axis.jsx
- src/components/LineChart/examples/5.all-the-things.jsx
Fixes #325 
`minor`: improved `LineChart` and `BarChart` to merge default margins with the `margin` prop so you can still retain defaults if you only want to override some of them
> Default chart margins improvement

- src/components/Checkbox/Checkbox.jsx
- src/components/RadioButton/RadioButton.jsx
fixes #338 
http://docspot.devnxs.net/projects/lucid/bugfix-338-checkbox-radiobutton/
> remove redundant events from radiobutton and checkbox

- src/components/Icon/RefreshIcon/RefreshIcon.jsx
- src/components/Icon/RefreshIcon/RefreshIcon.spec.jsx
- src/components/Icon/RefreshIcon/examples/default.jsx
- src/index.js
- `minor`: added new `RefreshIcon` component
Fixes #327.
> Added refresh icon #327

- src/components/SingleSelect/SingleSelect.jsx
fixes #194 
- `patch`: fixed `SingleSelect` to allow tabbing (i.e. added tabindex)
> add tabIndex to SingleSelect control

- src/components/Paginator/Paginator.jsx
- src/components/Paginator/Paginator.spec.jsx
fixes #347 
`Paginator.handleTextFieldChange` expects `(value, totalPages)`. But instead, is receiving the following from `TextField.onSubmit`: `(value, {event, props: this.props })`.
In `Paginator.reducers.onPageSelect`, `selectedPageIndex` always gets set to `0` ->
`selectedPageIndex: _.clamp(pageIndex, 0, totalPages - 1)`, where `totalPages` is an object, not a number.
The fix was to calculate the correct value for `totalPages` in `Paginator.handleTextFieldChange` based on `totalCount` and `selectedPageSizeIndex` and pass that to `Paginator.reducers.onPageSelect`.
Not 100% sure about this. Do we need to pass the event?
> #347: Fixed Paginator bug that was causing textfield to revert to the default value onChange

- src/components/Autocomplete/Autocomplete.jsx
fixes #313
fixes #314 
http://docspot.devnxs.net/projects/lucid/313-autocomplete-private/#/components/Autocomplete
> 313 autocomplete private / 314 remove caret

- src/components/Button/Button.jsx
- src/components/Button/Button.spec.jsx
> default Button type='button' - to avoid accidental trigger onEnter elsewhere

- .travis.yml
- scripts/validate-tests.sh
This adds a check in travis for `.spec.` files that contain `.only` in them. It should fail the build before even installing any npm packages.
Fixes #415
> Check tests for .only

- src/components/Button/Button.less
fixes #324 
http://docspot.devnxs.net/projects/lucid/324-button-wrapping/#/components/Button
> fix wrapping of Button contents

- src/components/Sidebar/Sidebar.jsx
- src/components/Sidebar/Sidebar.spec.jsx
- src/components/Sidebar/examples/8.handle-toggle-and-resize.jsx
- src/components/SplitVertical/SplitVertical.jsx
- src/components/SplitVertical/SplitVertical.spec.jsx
> Add `onResizing` event handler to SplitVertical and Sidebar.

- src/components/Expander/Expander.less
- src/components/ExpanderPanel/ExpanderPanel.less
- src/components/Icon/ChevronIcon/ChevronIcon.jsx
- src/components/Icon/ChevronIcon/ChevronIcon.less
- src/components/Sidebar/Sidebar.less
- src/components/VerticalListMenu/VerticalListMenu.less
- Fixes #399 
- Fixed all the usages of ChevronIcon to work with `fill` instead of `stroke`
- The bottom of the ChevronIcon wasn't properly rounded, I fixed that too
> Switch ChevronIcon to fill

- src/components/Button/Button.jsx
- src/components/Button/Button.less
- src/components/Button/Button.spec.jsx
- src/components/Button/examples/basic.jsx
- src/components/Button/examples/danger.jsx
- src/components/Button/examples/info.jsx
- src/components/Button/examples/link.jsx
- src/components/Button/examples/primary.jsx
- src/components/Button/examples/success.jsx
- src/components/Button/examples/warning.jsx
- src/components/Paginator/Paginator.jsx
- src/components/Paginator/Paginator.less
- src/docs/containers/icons.jsx
`patch`: fixed issue with buttons that had an icon and text nodes as siblings that were incorrectly styled with react 15. Added a new prop to `Button` called `hasOnlyIcon` that can be flipped on for buttons that should only contain a single icon.
Fixes #441
> Button icons fix

- src/components/SingleSelect/SingleSelect.less
- src/components/SingleSelect/examples/07.max-menu-height.jsx
>  bugfix/456: add whitespace 'nowrap' for SingleSelect

- src/components/Accordion/Accordion.jsx
- src/components/Accordion/Accordion.spec.jsx
> Pass thru className from Accordian.Item to the rendered item element.

- src/components/ContextMenu/ContextMenu.jsx
- src/components/DropMenu/DropMenu.jsx
- src/components/TextField/TextField.jsx
- src/components/ToolTip/ToolTip.jsx
- src/util/redux.js
- src/util/redux.spec.js
Our pattern of passing the underlying event as the last argument of
event handlers was causing generated action creators to get called with
the event, which at some point gets traversed, and the property access
throws a warning synthetic event pooling warning.
The events are never actually used by any of the reducers, so the
warning is benign afaict, so I'm only stripping them in dev mode.
~~The code is a little uglier than it could be because we're not
completely consistent about where the event goes (sometimes the last arg
is an object `{ props, event }`, sometimes the event itself).~~ fixed all the consistency …
> strip synthetic events from action creator args in dev mode

- src/components/Sidebar/Sidebar.less
- src/components/Submarine/Submarine.less
of Sidebar and Submarine on collapse.
> Make small style tweaks to fully hide the divider

- src/components/SingleSelect/SingleSelect.less
> SingleSelect - add border-radius style to :before control

- src/components/BarChart/BarChart.jsx
- src/components/BarChart/BarChart.spec.jsx
- src/components/Bars/Bars.jsx
- src/components/Bars/Bars.spec.jsx
- src/components/Legend/Legend.jsx
- src/components/Legend/Legend.less
- src/components/Legend/examples/basic.jsx
- src/components/LineChart/LineChart.jsx
- src/components/LineChart/LineChart.spec.jsx
- src/components/LineChart/examples/4.multi-with-legend.jsx
- src/components/LineChart/examples/8.stacked-single-series-with-formatters.jsx
- src/components/LineChart/examples/9.stacked-monochrome-no-shapes.jsx
- src/components/PieChart/PieChart.jsx
- src/components/PieChart/PieChart.less
- src/components/PieChart/PieChart.spec.jsx
- src/components/PieChart/examples/6.small-with-no-stroke-or-hover.jsx
Fixes #478 added hasStroke to PieChart
Fixes #481 by adding a `hasToolTipTitles` to bar, line, and bars
Fixes #498 by tweaking the tooltip/legend logic on line charts
> Chart tweaks

- src/components/LoadingIndicator/LoadingIndicator.jsx
- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~
Fixes #511
> Make LoadingIndicator use Light variant by default

- package.json
- scripts/build-bundle.sh
- webpack.config.bundle.js
Fixes #525 by adding a bundled build of lucid to the `npm run preversion` command.
- ~~PR has one of the `semver-` labels~~
> Add browser build of lucid

- src/components/Checkbox/Checkbox.jsx
- src/components/Checkbox/Checkbox.less
- src/components/Checkbox/Checkbox.spec.jsx
- src/components/Checkbox/examples/interactive.jsx
- src/components/CheckboxLabeled/CheckboxLabeled.jsx
fixes #547 
http://docspot.devnxs.net/projects/lucid/547-checkbox-indeterminate/#/components/Checkbox
> 547 checkbox indeterminate

- src/components/Table/Table.jsx
> Issue #549: Prevent click event after resize

- src/components/DataTable/DataTable.jsx
> Makes the default EmptyMessageTitle more generic

- src/components/OverlayWrapper/OverlayWrapper.less
> Reverts OverlayWrapper to be `display: block`.

- src/components/DataTable/DataTable.jsx
- src/components/DataTable/DataTable.spec.jsx
- src/components/DataTable/examples/9.loading.jsx
- src/components/DataTableWrapper/DataTableWrapper.jsx
- src/components/DataTableWrapper/DataTableWrapper.less
- src/index.js
- src/styles/components.less
> Adds an `isLoading` prop to `DataTable`

- src/components/DropMenu/DropMenu.jsx
- src/util/dom-helpers.js
- src/util/dom-helpers.spec.js
> Adds `additionalOffset` to `scrollParentTo`.

- src/components/CheckboxLabeled/CheckboxLabeled.jsx
- src/components/CheckboxLabeled/CheckboxLabeled.less
- src/components/CheckboxLabeled/examples/interactive.jsx
- src/components/RadioButtonLabeled/RadioButtonLabeled.jsx
- src/components/RadioButtonLabeled/RadioButtonLabeled.less
- src/components/RadioButtonLabeled/examples/interactive.jsx
- src/components/RadioGroup/RadioGroup.spec.jsx
Fixes #529.
Docs here: http://docspot.devnxs.net/projects/lucid/529-improve-label-alignment/#/components/RadioButtonLabeled
This doesn't make a change to `SwitchLabeled` because it doesn't look like the text for that component wraps with longer labels.
> Updates label alignment for long labels.

- src/components/BarChart/BarChart.jsx
- src/components/BarChart/BarChart.spec.jsx
- src/components/BarChart/examples/9.formatted-tooltips.jsx
- src/components/LineChart/LineChart.jsx
- Add `yAxisTooltipDataFormatter` to `BarChart`
- In `LineChart`, cleanup defaults for `yAxisFormatter` and `y2AxisFormatter`
- In `BarChart`, cleanup defaults for `yAxisFormatter`
Fixes #566
> #566: Add yAxisTooltipDataFormatter prop to BarChart

- src/components/LineChart/LineChart.jsx
- src/components/LineChart/examples/11.color-offset.jsx
> Fixes issue #568. Adjust colorOffset of lines and points

- src/components/Legend/Legend.jsx
> Fix issue #564. Pass appropriate props to Legend.Item

- src/components/Tabs/Tabs.less
Fixes #563 
Docs uploaded here: http://docspot.devnxs.net/projects/lucid/563-tab-width/
> Switches Tab flex-basis to ensure even width.

- src/components/Tabs/Tabs.less
> #544: Don't show gray bottom border when a complex tab is active

- src/components/DataTable/DataTable.jsx
- src/components/DataTable/DataTable.less
- src/components/DataTable/DataTable.spec.jsx
- src/components/DataTable/examples/6.empty.jsx
- src/components/DataTable/examples/7.empty-with-custom-title-and-body.jsx
- src/components/DataTable/examples/8.empty-with-image.jsx
- src/components/DataTable/examples/9.loading.jsx
- src/styles/components.less
> Adds `isFullWidth` prop to `DataTable`.

- src/components/Tabs/Tabs.jsx
- src/components/Tabs/Tabs.spec.jsx
- src/components/Tabs/examples/5-tab-as-prop.jsx
Fleshes out `Tab` child component.
Fixes #579
> Fixes `onSelect` being called despite `isDisabled`

- src/components/Validation/Validation.jsx
use case here is sometimes I want to show an invalid state for `TextFieldValidated` for example, but without a message, because I have the validation message at a parent component level. So I want the styling, but I don't want the extra div because that messes with layout.
> allow validation styling without an error message

- src/components/TextField/TextField.jsx
- src/components/TextFieldValidated/TextFieldValidated.jsx
> propagate native element refs and add focus methods

- src/components/TextFieldValidated/TextFieldValidated.jsx
- src/components/TextFieldValidated/TextFieldValidated.spec.jsx
> remove redundant propTypes from TextFieldValidated

- src/util/generic-tests.jsx
> removes warnings from tests about calling PropType validation fns

- src/components/DataTable/DataTable.jsx
- src/components/DataTable/DataTable.spec.jsx
- src/components/Table/Table.jsx
- src/components/Table/Table.less
- src/components/Table/Table.spec.jsx
> Updates `emptyCell` to use `--`.

- src/components/Tabs/Tabs.less
> add margin in Tabs content to offset tab negative margin

- src/components/SearchField/SearchField.jsx
- src/components/SearchField/SearchField.spec.jsx
- src/components/SearchField/__snapshots__/SearchField.spec.jsx.snap
- src/components/SearchField/examples/8.props.jsx
- src/components/SearchableSelect/SearchableSelect.jsx
- src/index.js
> Searchfield export

- .eslintrc
- src/components/DataTable/DataTable.jsx
- src/components/ToolTip/ToolTip.jsx
- src/util/redux.js
- src/util/redux.spec.js
Prevents the situation where arrow functions are used ambiguously with conditional expressions
http://eslint.org/docs/rules/no-confusing-arrow
> Added `no-confusing-arrow` lint rule with fixes

- .eslintrc
- src/components/Autocomplete/Autocomplete.spec.jsx
- src/components/AxisLabel/AxisLabel.spec.jsx
- src/components/Panel/Panel.spec.jsx
> Added `no-multiple-empty-lines` lint rule with fixes

- src/components/Icon/ArrowIcon/ArrowIcon.less
- src/components/Icon/CaretIcon/CaretIcon.less
- src/components/SearchableSelect/SearchableSelect.jsx
- src/components/SearchableSelect/SearchableSelect.less
- src/components/SingleSelect/SingleSelect.jsx
- src/components/SingleSelect/SingleSelect.less
- src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
~~[ ] One core team UX approval~~
Fixes #649
> Removes redundant CSS from Arrow and Caret icons

- src/components/Panel/Panel.less
> Fixes #657 by setting flex-shrink: 0 to header/footer

- src/components/SplitButton/SplitButton.less
~~[ ] One core team UX approval~~
> Fixes weird typo in selector

- src/components/Checkbox/Checkbox.jsx
- src/components/Checkbox/Checkbox.spec.jsx
- src/components/Checkbox/__snapshots__/Checkbox.spec.jsx.snap
- src/components/RadioButton/RadioButton.jsx
- src/components/RadioButton/RadioButton.spec.jsx
- src/components/RadioButton/__snapshots__/RadioButton.spec.jsx.snap
> Fix double firing touch events

- src/components/VerticalListMenu/VerticalListMenu.jsx
- src/components/VerticalListMenu/__snapshots__/VerticalListMenu.spec.jsx.snap
- src/components/VerticalListMenu/examples/4.no-animations.jsx
Fixes #684 
http://docspot.devnxs.net/projects/lucid/684-collapsible-props-on-verticallistmenu/#/components/VerticalListMenu
> Add Collapsible props to VerticalListMenu.Item

- src/components/Resizer/Resizer.jsx
- src/components/Resizer/Resizer.spec.jsx
- src/components/Resizer/Resizer.util.js
the existing module exports an instance of `element-resize-detector` which tries to bind event listeners on `document.body` which may not be available at instantiation.
> create scroll listener on mount instead of exported singleton

- README.md
- gulp/build.js
- package.json
- src/util/dom-helpers.spec.js
> Fix path imports

- src/util/state-management.js
Fix bug where hybrid component reducers called in the same tick would overwrite the last state.
> Fix async hybrid setState overwrite bug.

- src/components/ContextMenu/ContextMenu.jsx
- src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
- src/components/RadioGroup/examples/nested-select.jsx
- src/util/dom-helpers.js
- src/util/dom-helpers.spec.js
Fixes #662
Detects if a body click was a `<label>` and doesn't trigger the on click
out handler if that's the case.
> Fix SingleSelect in RadioGroup bug

- src/components/DateSelect/DateSelect.jsx
> DateSelect render range of 1 day as a single selected day.

- src/components/SplitHorizontal/SplitHorizontal.jsx
- src/components/SplitVertical/SplitVertical.jsx
- src/components/Submarine/__snapshots__/Submarine.spec.jsx.snap
- src/components/Submarine/examples/10.hidden-bar.jsx
* Add check for changes in `collapseShift` in SplitHorizontal/SplitVertical
* Modify Submarine example to toggle `isHidden` property
http://docspot.devnxs.net/projects/lucid/bugfix-splithorizontal-check-collapseshift/#/components/Submarine
(_Hidden Bar_ example)
> Check for `collapseShift` changes in SplitHorizontal/SplitVertical

- src/components/TextField/TextField.jsx
if the TextField is unmounted before setState is called, an error is thrown. this checks to see if it is mounted before setting state.
strategy taken from https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html
> only setState on TextField when mounted

- src/components/SplitButton/SplitButton.jsx
> Disable SplitButton caret when all child Buttons are disabled

- src/components/SplitButton/SplitButton.jsx
> SplitButton: Fix to pass thru primary button className

- src/components/Icon/HelpIcon/HelpIcon.less
- src/styles/components.less
> change default HelpIcon colors

- src/components/RadioButtonLabeled/RadioButtonLabeled.less
- src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
- src/components/RadioGroup/examples/nested-select.jsx
RadioButton selected styles are being passed down to children.
before:
after:
> RadioButton specific selector to not pass selected style to children

- src/components/Sidebar/Sidebar.jsx
- src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap
fixes #801 
http://docspot.devnxs.net/projects/lucid/801-sidebar-gripper/
> Sidebar: fix gripper icon centering

- src/components/Tag/Tag.less
- src/styles/variables.less
> 821 - update tag styling to mitigate having too much concentrated teal

- src/components/Tabs/Tabs.jsx
- src/components/Tabs/Tabs.less
- src/components/Tabs/Tabs.spec.jsx
- src/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- src/components/Tabs/examples/6-tabs-variable-width.jsx
- src/components/Tabs/examples/7-navigation-tabs.jsx
- [/] Chrome
- [/] Firefox
- [/ ] PR has one of the `semver-` labels
> 831: Add navigation and variable width styling props for Tabs

- package.json
- src/components/Button/Button.jsx
- src/components/Button/Button.less
- src/components/Button/__snapshots__/Button.spec.jsx.snap
- src/components/Button/examples/basic.jsx
- src/components/Button/examples/danger.jsx
- src/components/Button/examples/info.jsx
- src/components/Button/examples/invisible.jsx
- src/components/Button/examples/link.jsx
- src/components/Button/examples/primary.jsx
- src/components/Button/examples/success.jsx
- src/components/Button/examples/warning.jsx
- src/components/Dialog/__snapshots__/Dialog.spec.jsx.snap
- src/components/Dialog/examples/1.small.jsx
- src/components/Dialog/examples/2.medium.jsx
- src/components/Dialog/examples/3.large-with-rich-header.jsx
- src/components/Dialog/examples/4.no-modal.jsx
> 828: revert link styling for button and add new kind "invisible"

- package.json
- src/components/Autocomplete/Autocomplete.spec.jsx
- src/components/BarChart/BarChart.spec.jsx
- src/components/ContextMenu/ContextMenu.jsx
- src/components/ContextMenu/ContextMenu.spec.jsx
- src/components/DateSelect/DateSelect.jsx
- src/components/DateSelect/DateSelect.less
- src/components/DateSelect/__snapshots__/DateSelect.spec.jsx.snap
- src/components/DateSelect/examples/8.disable-slide-panel.jsx
- src/components/DropMenu/DropMenu.spec.jsx
- src/components/SearchableSelect/SearchableSelect.spec.jsx
- src/components/SingleSelect/SingleSelect.spec.jsx
- src/components/ToolTip/ToolTip.spec.jsx
- Adds new prop `useSlidePanel` to DateSelect for finer control of performance
- reduces number of re-renders and state changes in ContextMenu
- ContextMenu FlyOut now uses requestAnimationFrame to synchronize alignments
> Perf improvements for DateSelect and ConextMenu

- src/components/DateSelect/DateSelect.jsx
- src/components/DateSelect/DateSelect.less
- src/components/DateSelect/__snapshots__/DateSelect.spec.jsx.snap
- src/components/DateSelect/examples/8.disable-slide-panel.jsx
- fixed bug in month offset logic that caused it to skip months
- fixed style bugs when rendering dividers `useSlidePanel` set to `false`
> Fix bugs in DateSelect

- src/components/IconSelect/IconSelect.less
- src/components/IconSelect/IconSelect.spec.js
fixes #881
http://docspot.devnxs.net/projects/lucid/881-icon-select-hover-glow/#/components/IconSelect
> IconSelect: fix hover glow when selected

- src/components/Panel/Panel.jsx
> Set `propName: 'Panel'` on the Panel component.

- src/components/Lines/Lines.jsx
- src/components/Lines/__snapshots__/Lines.spec.jsx.snap
This seems to be caused by a bug with chrome's painting optimization of svg paths.
> Fix for chrome bug for 0-slope Lines being clipped

- src/components/BarChart/BarChart.jsx
- src/components/DataTable/DataTable.jsx
- src/components/DateSelect/DateSelect.jsx
- src/components/InfiniteSlidePanel/InfiniteSlidePanel.jsx
- src/components/LineChart/LineChart.jsx
- src/components/LoadingIndicator/LoadingIndicator.jsx
- src/components/SearchField/SearchField.jsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
- src/components/SearchableSelect/SearchableSelect.jsx
addresses #879 
uses codemod: https://gist.github.com/jhsu/94d876d980d5c5fcc313063d10f6f36d
> only construct an element when getFirst does not

- src/components/Tabs/Tabs.jsx
- src/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- src/components/Tabs/examples/01-title-as-prop.jsx
> Tabs: don't overwrite className of child Tab

- src/components/BarChart/BarChart.jsx
- src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
> BarChart: pass along `xAxisFormatter` to Axis prop `tickFormat`

- src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
- src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap
- src/components/Submarine/__snapshots__/Submarine.spec.jsx.snap
- src/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- src/components/VerticalListMenu/__snapshots__/VerticalListMenu.spec.jsx.snap
- src/docs/index.jsx
- src/util/state-management.js
Reverted changes to exposed defaultProps in buildHybridComonent stateful wrapper. This was causing props which were passed in explicitly, but had the same value as the default prop to be ignored. For doc generation, a static property `peekDefaultProps` was exposed to inspect default values.
> Revert exposing defaultProps in buildHybridComonent

- src/components/Portal/Portal.jsx
> Unmount Portal at DOM node before removing it

- src/util/state-management.js
Ensure that initial state of hybrids is not populated by passed props other than `initialState`
> Fix initial state bug

- src/components/LineChart/LineChart.jsx
- src/components/LineChart/__snapshots__/LineChart.spec.jsx.snap
- src/components/LineChart/examples/16.fine-grained-ticks.jsx
There have been some use cases where people need finer grain control
over the x axis tick marks on the line chart. This PR should enable
that.
> Add fine grained tick control

- src/components/SplitButton/SplitButton.jsx
- src/components/SplitButton/__snapshots__/SplitButton.spec.jsx.snap
- src/components/SplitButton/examples/4.sizes.jsx
> fix secondary button size in `SplitButton`

- .storybook/lucid-docs-addon/ChildComponents.js
- .storybook/lucid-docs-addon/PropTypes.js
- .storybook/lucid-docs-addon/index.js
- .storybook/lucid-docs-addon/register.js
- docs/examples/Accordion.stories.js
- docs/index.stories.js
- src/components/Sidebar/Sidebar.jsx
- src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap
- src/components/TextField/TextField.jsx
Added Child components to docs in the 'Props' panel.
See http://docspot.devnxs.net/projects/lucid/docs-child-components/?selectedKind=Accordion&selectedStory=basic&full=0&addons=1&stories=1&panelRight=1&addonPanel=lucid-docs-panel-props
> Add child components to docs

- .storybook/lucid-docs-addon/index.js
- docs/examples/SearchableMultiSelect.stories.js
- docs/examples/SearchableMultiSelect/WithFormattedOptions.js
- docs/examples/SearchableSelect.stories.js
- docs/examples/SearchableSelect/WithFormattedOptions.js
- docs/examples/SingleSelect.stories.js
- docs/examples/SingleSelect/WithFormattedOptions.js
- docs/examples/Underline.stories.js
- docs/examples/Underline/WithDefaults.js
- docs/examples/Underline/WithRegexMatch.js
- docs/examples/Underline/WithStringMatch.js
- src/components/DropMenu/DropMenu.jsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.spec.jsx
- src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.jsx.snap
- src/components/SearchableSelect/SearchableSelect.jsx
- src/components/SearchableSelect/SearchableSelect.spec.jsx
- src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap
- src/components/SingleSelect/SingleSelect.jsx
- src/components/SingleSelect/SingleSelect.spec.jsx
- src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
- src/components/Underline/Underline.jsx
- src/components/Underline/Underline.spec.jsx
- src/components/Underline/__snapshots__/Underline.spec.jsx.snap
- src/index.js
- src/util/generic-tests.jsx
- src/util/text-manipulation.js
- src/util/text-manipulation.spec.js
Added more formatting options to `SingleSelect`, `SearchableSelect`, and `SearchableMultiSelect`:
- Added new component `Underline` that will underline child text that matches a given text pattern
- `Option` accepts a `Selected` prop/child that is rendered when the option is selected
- `Option` children accepts a function/component as children which is passed the current `searchText` as a prop
> Selector option formatting

- src/components/Portal/Portal.jsx
In Portal, pass along the `store` context property to rendered Portal children
> Portal: pass store context to children

- src/components/TextField/TextField.jsx
- src/components/TextField/TextField.spec.jsx
> #939: flushing onChangeDebounced when blurring or submitting

- src/components/Axis/Axis.jsx
- src/components/Axis/__snapshots__/Axis.spec.jsx.snap
- src/components/Axis/examples/2.bottom.jsx
- src/components/Axis/examples/3.top.jsx
- src/components/Axis/examples/5.right.jsx
- src/components/Axis/examples/8.diagonal-text.jsx
- src/components/BarChart/BarChart.jsx
- src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
- src/components/BarChart/examples/01.basic.jsx
- src/components/BarChart/examples/13.many-bars.jsx
- src/components/LineChart/LineChart.jsx
- src/components/LineChart/__snapshots__/LineChart.spec.jsx.snap
- src/components/LoadingIndicator/__snapshots__/LoadingIndicator.spec.jsx.snap
- src/components/OverlayWrapper/__snapshots__/OverlayWrapper.spec.jsx.snap
> Fixes ANXR-1520 by adding diagonal tick labels to `Axis`

- src/components/Bar/Bar.jsx
- src/components/Bar/__snapshots__/Bar.spec.jsx.snap
- src/components/Bar/examples/custom-dimension-units.jsx
> Fixes #955 by allowing Bar component to accept both string and number type for dimension.

- src/components/Tabs/Tabs.less
- src/components/VerticalListMenu/VerticalListMenu.less
> Fixes #943 by changing unselected tab color to @color-darkGray

- src/components/Sidebar/Sidebar.less
this adds display flex to the sidebar so that additionally users can add display flex to the `.lucid-Sidebar-Bar-content` and allow the sidebar content to be scrolled separately from the header.
without this it would shrink the header:
> flex sidebar and don't shrink the header

- docs/examples/SidePanel.stories.js
- docs/examples/SidePanel/NoModal.js
Preview here: https://docspot.adnxs.net/projects/lucid/966-sidepanel-no-overlay-example/?selectedKind=SidePanel&selectedStory=no%20modal
> Fixes #966 by adding `SidePanel` example showing `isModal` set to false

- src/util/component-types.js
- src/util/state-management.js
> fix failing object checks that broke after the babel 7 upgrade

- package.json
treeshaking was removing less/css from our production build.  Looks good now.
https://docspot.adnxs.net/projects/lucid/allow-css-side-effects/?selectedKind=SearchField&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=lucid-docs-panel-props
> whitelist css as side effects

- src/components/Table/Table.jsx
Simple prop change.
width can be a number but can also be a string (i.e. '20%')
> Fix prop warnings for valid props

- src/components/ContextMenu/ContextMenu.jsx
- src/components/ContextMenu/__snapshots__/ContextMenu.spec.jsx.snap
- src/components/DropMenu/DropMenu.jsx
- src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
- src/components/Overlay/Overlay.jsx
- src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
- src/components/RadioGroup/RadioGroup.jsx
- src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
- src/util/style-helpers.js
- src/util/style-helpers.spec.js
- tests/init.js
safeguard against duplicate portal ids when (for some not ideal reason) multiple instances of the lucid library are loaded by consumer apps
- [ x Unit tests written (`common` at minimum)
> safeguard against duplicate portal ids

- src/components/Axis/__snapshots__/Axis.spec.jsx.snap
- src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
- src/components/SidePanel/SidePanel.jsx
- src/components/SidePanel/SidePanel.less
- src/components/SidePanel/SidePanel.spec.jsx
- src/components/SidePanel/__snapshots__/SidePanel.spec.jsx.snap
Pass the `onCollapse` click handler to the `Button` rather than the `CloseIcon`.
Since the button has some padding, there are clickable areas on the button that do not trigger the panel to collapse.
> close the panel when the button is clicked, not the icon

- src/components/Portal/Portal.jsx
- src/components/Portal/Portal.spec.jsx
- src/components/Portal/examples/basic.jsx
- src/components/Portal/examples/context.jsx
lucid's portal implementation loses react context.
This pull request changes the portal implementation to use `React.createPortal` to [ensure that context is preserved](https://reactjs.org/docs/portals.html).
An example using context has been added.
> use react to create a portal so that context is available

- src/components/Paginator/Paginator.jsx
- src/components/Paginator/Paginator.less
- src/components/Paginator/Paginator.spec.jsx
- src/components/Paginator/__snapshots__/Paginator.spec.jsx.snap
- src/components/Paginator/examples/4.show-object-count.jsx
Adds the ability to show the `totalCount` to the left side of the `Paginator`.
Additional props `objectLabel` and `objectLabelPlural` to customize the text after the total count number. 
This does not affect how the `Paginator` appears when `showTotalObjects` is not provided.
- Paginator
- new props: `showTotalObjects`, `objectLabel`, `objectLabelPlural`
> add prop to Paginator to show total count

- src/components/Expander/Expander.jsx
- src/components/Expander/Expander.less
- src/components/Expander/Expander.spec.jsx
- src/components/Expander/__snapshots__/Expander.spec.jsx.snap
- src/components/Expander/examples/4.interactive-with-changing-labels-and-additional-label-content.jsx
With a current implementation of **Expander**,  transition causes some flickering. 
Also in order to display any additional div or text on the same line as Expander Label, the div needs to be passed outside the **Expander** and then some absolute positioning needs to be applied to this div, as well as moving if to the right by 125px, and moving down the Expander Label to make sure, that they all are located on the same line.
Now you can pass an additional div, that you want to display on the same line with **AdditionalLabelContent** prop. Let me know pls if there is a better naming for it or some other comments regarding this PR.
> Additional expander label data and remove transition

- src/components/SlidePanel/SlidePanel.jsx
- src/components/Table/Table.jsx
- src/components/Tabs/Tabs.jsx
- src/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
- src/components/Tabs/examples/09-with-count.jsx
> Fixes #990 by allowing any number to be passed as count value (even 0).

- src/components/SidePanel/SidePanel.less
This fixes SidePanel scrolling is able to show all content, even with top offset.
previously, the sidepanel would bleed below the viewport resulting in content that went offscreen.
The fix involves using `height: auto` and setting top, bottom and left/right to 0, since the panel is `display: fixed;`. This allows a margin-top to be applied without pushing it below the viewport.
working version:
> fix SidePanel's content heights 

- src/components/SearchField/SearchField.jsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
- src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.jsx.snap
- src/components/SearchableSelect/SearchableSelect.jsx
- src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap
- src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
- src/components/SearchableSingleSelect/__snapshots__/SearchableSingleSelect.spec.jsx.snap
> default autoComplete attribute to off for searchable controls

- src/components/DataTable/DataTable.jsx
- src/components/DataTable/DataTable.spec.jsx
- src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
use the header CheckBox to indicate when rows are partially selected versus all rows being selected.
One thing I noticed is that when checking if all rows are selected, our logic checks all row data for `isSelected` but does not esxclude `isDisabled` rows. Is that something we might want to do? (probably a separate pull-request)
> use an indeterminate state for DataTable select all when partially selected

- src/components/SidePanel/SidePanel.less
Only the close icon should be gray in the header
> fix greedy SidePanel css selector.  

- docs/load-components.js
- src/components/Typography/Typography.jsx
- src/components/Typography/Typography.less
- src/components/Typography/Typography.spec.jsx
- src/components/Typography/__snapshots__/Typography.spec.jsx.snap
- src/components/Typography/examples/01.variants.jsx
- src/components/Typography/examples/02.nested.jsx
- src/index.js
- src/styles/components.less
First pass is done. I can think of a ton of features we could add, but it could expand the API needlessly. I would say we should poll the library consumers to see the most common styles that are added to generic text components, so maybe we could generate those via props instead (allowing for DRYer code).
Docspot: https://docspot.adnxs.net/projects/lucid/typography-component/?selectedKind=Typography&selectedStory=variants&full=0&addons=1&stories=1&panelRight=1&addonPanel=lucid-docs-panel-props
> Typography component

- src/components/DataTable/DataTable.jsx
show an unchecked checkbox when the `DataTable` is selectable, but data is empty.
/cc @rsadres
> show an unchecked checkbox when DataTable is empty

- src/components/SidePanel/SidePanel.jsx
- src/components/SidePanel/SidePanel.spec.jsx
When using the `preventBodyScroll` prop on `SidePanel` and the `SidePanel` unmounts, it leaves behind `overflow: hidden` on the body.
This can happen when you navigate to a different page.
> remove hidden overflow from body when SidePanel unmounts

- docs/load-components.js
- src/components/DataTable/DataTable.spec.jsx
- src/components/DraggableList/DraggableList.jsx
- src/components/DraggableList/DraggableList.less
- src/components/DraggableList/DraggableList.reducers.js
- src/components/DraggableList/DraggableList.reducers.spec.js
- src/components/DraggableList/DraggableList.spec.jsx
- src/components/DraggableList/__snapshots__/DraggableList.spec.jsx.snap
- src/components/DraggableList/examples/1.basic.jsx
- src/components/DraggableList/examples/2.no-drag-handle.jsx
- src/components/DraggableList/examples/3.with-children.jsx
- src/components/Typography/examples/01.variants.jsx
- src/components/Typography/examples/02.nested.jsx
- src/index.js
- src/styles/components.less
Adds a basic list component that allows rearranging items by drag and drop: https://github.com/appnexus/lucid/issues/1009.
> Add component to render a drag and drop list

- src/components/StickySection/StickySection.jsx
- src/components/StickySection/__snapshots__/StickySection.spec.jsx.snap
- src/components/StickySection/examples/4.top-offset.jsx
When using `StickySection`, it sticks to the top of the document, but if there is a navbar or some content above, it will overlap.
This adds a new `topOffset` prop that will use it as a top threshold before it becomes sticky. It will display with that `topOffset` when sticky.
> Add topOffset prop to the StickySection

- package-lock.json
- src/components/ToolTip/ToolTip.less
> CXP-719: #1020 Fixed light tooltip link color and dark tooltip border color

- package-lock.json
- src/components/Button/__snapshots__/Button.spec.jsx.snap
- src/components/Button/examples/all-types.jsx
- src/styles/variables.less
DocSpot: https://docspot.adnxs.net/projects/lucid/673-disabled-button
> CXP 673: disabled buttons should have icon color that matches text

- src/components/DataTable/DataTable.jsx
- src/components/DataTable/DataTable.spec.jsx
- src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
- src/components/Table/Table.less
Adds a basic DataTable component that allows resizing column width by drag and drop:
> initial code changes for supporting column width resizer

- docs/color-palette.jsx
- docs/color-palette.less
- src/components/NotchedTag/NotchedTag.less
- src/styles/variables.less
This PR adds a new teal color and revamps the color palette a little bit to include all our shades of gray.
- ~~Chrome~~
- ~~Safari~~
> Add teal to secondary colors for NotchedTag and improve color palette

- src/components/Banner/Banner.jsx
- src/components/Banner/Banner.less
- src/components/Banner/__snapshots__/Banner.spec.jsx.snap
- src/components/Banner/examples/small.jsx
- src/components/Banner/examples/stateless.jsx
> Add outline-only version of Banner, defaults to filled version

- src/components/ContextMenu/ContextMenu.jsx
- src/components/DropMenu/DropMenu.less
- src/components/SingleSelect/SingleSelect.jsx
- src/components/SingleSelect/SingleSelect.less
- src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
Found several inconsistencies with the mock while working on this ticket:
- some margins/padding were 12px instead of 9px
- using a `border-bottom-width: 0` caused jitter when opening/closing the single select so I instead started using the offset prop that `ContextMenu` supports
- other code formatting stuff
Preview for Xandr employees only: https://docspot.adnxs.net/projects/lucid/single-select-styling-fix/?selectedKind=SingleSelect&selectedStory=basic&full=0&addons=1&stories=1&panelRight=1&addonPanel=lucid-docs-panel-props
> Align SingleSelect with Abstract mocks

- src/components/Bars/Bars.jsx
- src/components/Bars/Bars.spec.jsx
when formatting x or y for a bar, it can be useful for the formatter function to have access to the full data object.
This is useful when the bar is a sum of a range of data that has been grouped. for example a datum might look like: `{x: 1, y: 10, min: 0, max: 2}` we may want to format the display to show `0-2`.
> pass the data point to the xFormatter and yFormatter functions

- src/components/ToolTip/ToolTip.less
> CXP-719: #1031 fixed tooltip default carat border styling

- src/components/Banner/Banner.less
> Fix Banner warning close icon color

- package-lock.json
- package.json
- src/components/Selection/Selection.jsx
- src/components/Selection/__snapshots__/Selection.spec.jsx.snap
Passing nested children is the intended use-case, but if a consumer wants to to pass other children for special styling we shouldn't jumble up the order of the children on them.
I could put this change behind a prop flag, but I really feel like it's bug fix more than a breaking change.
> Selection should maintain the order of children passed in. 

- src/components/Icon/EligibilityIcon/EligibilityIcon.less
- src/components/Icon/EligibilityIcon/EligibilityIcon.tsx
- src/components/Icon/EligibilityIcon/__snapshots__/EligibilityIcon.spec.jsx.snap
- src/components/Icon/EligibilityLightIcon/EligibilityLightIcon.tsx
- src/components/Icon/EligibilityLightIcon/__snapshots__/EligibilityLightIcon.spec.jsx.snap
- ~Chrome~
- ~Safari~
- ~Edge (Win 10)~
> Normalize the size of the eligibility icons

- src/util/redux.spec.js
- src/util/redux.ts
- ~Manually tested across supported browsers~
> Fix redux util regression where `identity` was set to `noop`

- src/components/SearchField/SearchField.less
- src/components/TextField/TextField.less
search texts overlaps the search icon on the `SearchField` component
add a padding-right to the input
> set padding-right on SearchField

- src/components/IconSelect/IconSelect.tsx
- src/components/IconSelect/__snapshots__/IconSelect.spec.js.snap
when an item is marked as disabled (`isDisabled` on the item), you can still click on it to trigger the select event.
Instead, if an item is disabled, use `undefined` for `onClick`.
> onClick is still triggered when a disabled  IconSelect item is clicked

- src/components/DataTable/DataTable.jsx
update the document on the prop `fixedColumnCount` to be clear that it requires `hasFixedHeader`
> document fixedColumnCount requires hasFixedHeader

- src/components/OverlayWrapper/OverlayWrapper.less
Set z-index for `OverlayWrapper` to `@zindex-modal` so it is consistent with `Dialog` and `Overlay`.
> set OverlayWrapper z-index to zindex-modal

- package-lock.json
- src/components/Icon/WarningIcon/WarningIcon.tsx
- src/components/Icon/WarningIcon/__snapshots__/WarningIcon.spec.jsx.snap
- src/components/Icon/WarningLightIcon/WarningLightIcon.tsx
- src/components/Icon/WarningLightIcon/__snapshots__/WarningLightIcon.spec.jsx.snap
> Improved warning icon path to handle smaller sizes

- .storybook/lucid-docs-addon/util.js
This PR creates a consistent props table order in docs pages.   There will be three groups -- required props, child components, and the rest of the props.  Each group will be sorted alphabetically.
This PR also fixes a bug where `null` default props were not shown in the the props table.
> Docs consistent props order

- src/components/Icon/MinusCircleIcon/MinusCircleIcon.less
- src/components/Icon/MinusCircleLightIcon/MinusCircleLightIcon.less
- src/components/Icon/MinusCircleLightIcon/__snapshots__/MinusCircleLightIcon.spec.jsx.snap
- src/components/Icon/MinusCircleLightIcon/examples/1.default.jsx
- src/components/Icon/SuccessLightIcon/SuccessLightIcon.less
- src/components/Icon/SuccessLightIcon/__snapshots__/SuccessLightIcon.spec.jsx.snap
- src/components/Icon/SuccessLightIcon/examples/1.default.jsx
- src/styles/variables.less
Xandr employees can preview changes [here](https://docspot.adnxs.net/projects/lucid/light-icon-hover/?path=/docs/icons-icons-successlighticon--default)
> adjust hover colors for SuccessLightIcon and MinusCircleLightIcon

- webpack.config.bundle.js
I found that we accidentally stopped building a bundled CSS file when we removed the `import ... "index.less"` a while back. This really only affects our ability to use codepen, etc.
> Add the less file back as an entrypoint for our bundle build

- src/util/component-types.ts
Allow the notes property on FCs. Class components don't need any changes right now because they extend React.Component, so we don't have any specific type checking. That should be added in a later PR once we nail down the exact class component structure for hybrid components (for example, should the `peek`info be a property on the class or part of `statics`, will also depend on whether we use the existing createClass util or start to use a different pattern, etc.)
> add peek.notes property to functional component interface

- src/components/Collapsible/Collapsible.tsx
since `setState` is wrapped in a `_.delay`, we should ensure that the component is still mounted before we `setState`.
> collapsible should only setState if still mounted

- src/components/Icon/DangerLightIcon/DangerLightIcon.tsx
- src/components/Icon/InfoLightIcon/InfoLightIcon.tsx
- src/components/Icon/WarningLightIcon/WarningLightIcon.tsx
> Hide from docs: DangerLightIcon, InfoLightIcon, WarningLightIcon

- src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap
- src/components/Tag/Tag.less
- src/components/Tag/Tag.tsx
- src/components/Tag/__snapshots__/Tag.spec.jsx.snap
- src/components/Tag/examples/05.colors.jsx
Changes requested for Shedules on buyside
**Updated** - Examples now show the following:
removable tags keep their primary color border by default
> Tag border colors

- docs/index.stories.js
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/update-icon-color-examples/?path=/docs/icons--overview)
> add creative icon for icon color variation docs section

- src/components/Tag/Tag.less
- src/components/Tag/Tag.tsx
Avoid activating kind props on parent tags by using a recursive function to set the kind border color on leaves.
- Also removed the kind type of primary; since it isn't being assigned a style/used.
> Avoid adding kind border styles on parent tags

- docs/load-icons.js
- src/components/Icon/RunReportIcon/RunReportIcon.tsx
- src/components/Icon/RunReportIcon/RunRepotIcon.spec.jsx
- src/components/Icon/RunReportIcon/__snapshots__/RunRepotIcon.spec.jsx.snap
- src/components/Icon/RunReportIcon/examples/1default.jsx
- src/index.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/feature_cxp-923_run-report-icon/?path=/docs/icons-icons-runreporticon--default)
> Feature cxp 923 run report icon

- README.md
- docs/index.less
- src/index.less
This should have never been put in the main less file and was causing
blocking loading for external consumers of the library. I moved it into
the main less file for the docs page so we can continue to see the
custom font on the docs when we're on our VPN.
Storybook can be viewed [here]()
> Fix font loading

- src/components/RadioButtonLabeled/RadioButtonLabeled.tsx
Add div props to RadioButtonLabeled props interface. RadioGroupButtonLabel extends this, so it will have div props as well.
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-935_radio-group-label-div-attributes)
> add div props to radio button labeled

- src/components/DraggableList/__snapshots__/DraggableList.spec.jsx.snap
- src/components/Icon/DotsIcon/DotsIcon.tsx
- src/components/Icon/DotsIcon/__snapshots__/DotsIcon.spec.jsx.snap
- src/components/Icon/DotsIcon/examples/1.default.jsx
Add vertical option to the three dots icon.
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/txp-127-add-vertical-orientation-to-dots-icon/?path=/story/icons-icons-dotsicon--default)
> TXP-127 add vertical orientation to dots icon

- src/components/PieChart/PieChart.tsx
`PieChart` component has a `donutWidth` prop in it, but it is not used to control the width of the donut chart. It uses the default prop 15px value of `DONUT_WIDTH` all the time. Make it so if `donutWidth` prop passed then use its value, otherwise use `DONUT_WIDTH`
> Use donutWidth prop to control width of a donut chart

- src/components/Accordion/Accordion.tsx
- src/components/ExpanderPanel/ExpanderPanel.tsx
- src/components/PieChart/PieChart.tsx
- src/components/VerticalListMenu/VerticalListMenu.tsx
- src/components/VerticalTabs/VerticalTabs.tsx
- src/index.ts
This PR exposes each of the component interfaces for state and props, some of the subcomponent interfaces, and raw props interfaces at the package level so they can be used. There is an argument for exporting everything based on the situation so that's what I did. Let me know if you don't want anything exposed here.
> Expose component interfaces

- src/components/DropMenu/DropMenu.tsx
This PR extends the props interface for the `DropMenu` component to include passthrough props for a `div` element. Please let me know if I "over-used" this new interface, I was a bit unsure if the callback arguments for `onExpand`, `onCollapse`, etc., pass the component props with the pass-throughs, or just the internally defined props from `IDropMenuProps`
> extend DropMenu props to include div element passthroughs

- src/components/Bars/Bars.tsx
Small PR updating Bars props
First I updated renderTooltipBody to have a type of `number | string | object` instead of just number. Because I've seen instances of it being any of those, object in my specific case that this PR is addressing.
Second, ~I'm adding `transform` as a prop. Transform is an included attribute for svg's that is helpful to be used for tweaking the positioning of the Bars within axes.~ I've updated Bars to extend SVGProps props, to include `transform` and others
> BUDE-420: Update Bars props

- package.json
- src/index.ts
- tsconfig.json
This is technically a breaking change but I'm marking it as a patch since it was actually breaking in the first place when it was introduced.
I haven't investigated how to properly expose the types, but I'm sure it's possible in another manner.
> Fixes #1153 by removing features not compatible with babel ts

- src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
Fix SearchableSingleSelect warnings that appears when you select an item
> Fix SearchableSingleSelect warnings

- scripts/upload-docs-build-gh.sh
This should help folks who clone the repo with https.
> Improve the GH upload script to work with https

- src/components/DropMenu/DropMenu.spec.jsx
- src/components/DropMenu/DropMenu.tsx
> Issue 1164: Omit Selection prop from DropMenuOption prop types

- src/components/DraggableLineChart/DraggableLineChart.tsx
- src/components/DraggableLineChart/DraggableLineChartD3.ts
- src/components/DraggableLineChart/d3-helpers.ts
- src/components/DraggableLineChart/examples/02.ExampleWithExternalXAxisRenderProp.tsx
Fixed missing style line. We have also updated the component to always pass back x, y, and ref to each render prop. This will eliminate the need to the consumers to need to tie any data back to that component.
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-646-part2/?path=/docs/visualizations-draggablelinechart--example-with-external-x-axis-render-prop)
> BUDE-646: Fix missing line

- CHANGELOG.md
- src/components/LoadingIndicator/LoadingIndicator.less
- src/components/LoadingIndicator/LoadingIndicator.tsx
- src/components/LoadingIndicator/__snapshots__/LoadingIndicator.spec.jsx.snap
- src/components/OverlayWrapper/OverlayWrapper.less
- src/components/OverlayWrapper/OverlayWrapper.tsx
> BUDE-479: Add option to LoadingIndicator and OverlayWrapper to center loading message and prevent scrolling

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/DraggableLineChart/DraggableLineChart.less
- src/components/DraggableLineChart/DraggableLineChart.tsx
- src/components/DraggableLineChart/DraggableLineChartD3.ts
- src/components/DraggableLineChart/examples/03.ExampleWithNoDataWithPreselect.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-967/?path=/docs/visualizations-draggablelinechart--example-with-no-data-with-preselect)
> Bude 967: Add in helper text for draggable line chart

- src/components/DataTable/DataTable.jsx
- src/components/Table/Table.less
- src/components/Table/Table.spec.jsx
- src/components/Table/Table.tsx
> Bude 966: Add optional flag to truncate Table cell content with ellipsis when fixedHeader

- src/components/TimeSelect/TimeSelect.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-968/?path=/docs/*)
> BUDE-968: Toggle active class on clock icon on input focus

- src/components/SearchableSingleSelect/__snapshots__/SearchableSingleSelect.spec.jsx.snap
- src/components/SearchableSingleSelect/examples/07.formatted-options.tsx
Only adding an example, no code changes
> BUDE-969: Add formatted-options example to SearchableSingleSelect

- src/components/TextField/TextField.less
- src/components/TextField/TextFieldPlain.spec.jsx
- src/components/TextField/TextFieldPlain.tsx
- src/components/TextField/examples/plain.jsx
- src/index.ts
note: this is a redo of https://github.com/appnexus/lucid/pull/1193 to fix the chromatic build
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/textfield-plain/?path=/docs/controls-textfield--plain)
This adds a `TextFieldPlain` component. This is a super simple wrapper around input/textrea that has the same styling as `TextField` without the complex reducers or anything fancy.
I've found TextField's state management a bit much for most cases and just need a lucid styled textfield and especially this makes it easier for testing w/o requiring any re-renders.
> feat: add TextFieldPlain

- docs/load-components.js
- src/components/LoadingSkeletons/GroupLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/GroupLoadingSkeleton.tsx
- src/components/LoadingSkeletons/TableLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/TableLoadingSkeleton.tsx
- src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/1.basic.tsx
- src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/2.add-header.tsx
- src/components/LoadingSkeletons/examples/GroupLoadingSkeleton/3.two-rows-three-columns.tsx
- src/index.ts
Storybook can be viewed
https://docspot.adnxs.net/projects/lucid/BWAP-704_Add_GroupLoadingSkeleton_to_Lucid
> BWAP-704 Added GroupLoadingSkeleton 

- docs/load-components.js
- src/components/LoadingSkeletons/LineChartLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/LineChartLoadingSkeleton.tsx
- src/components/LoadingSkeletons/examples/LineChartLoadingSkeleton/1.basic.tsx
- src/components/LoadingSkeletons/examples/LineChartLoadingSkeleton/2.add-header.tsx
- src/components/LoadingSkeletons/examples/LineChartLoadingSkeleton/3.two-rows-two-columns.tsx
- src/index.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BWAP-708_Add_LineChartLoadingSkeleton_to_Lucid
)
> BWAP-708 Add LineChartLoadingSkeleton to Lucid

- docs/load-components.js
- src/components/LoadingSkeletons/SimpleTableLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/SimpleTableLoadingSkeleton.tsx
- src/components/LoadingSkeletons/examples/SimpleTableLoadingSkeleton/1.basic.tsx
- src/components/LoadingSkeletons/examples/SimpleTableLoadingSkeleton/2.add-header.tsx
- src/components/LoadingSkeletons/examples/SimpleTableLoadingSkeleton/3.three-rows-one-column.tsx
- src/index.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BWAP-709_Add_SimpleTableLoadingSkeleton_to_Lucid
)
> BWAP-709 Added SimpleTableSkeleton

- docs/load-components.js
- src/components/LoadingSkeletons/SingleLineLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/SingleLineLoadingSkeleton.tsx
- src/components/LoadingSkeletons/examples/SingleLineLoadingSkeleton/1.basic.tsx
- src/components/LoadingSkeletons/examples/SingleLineLoadingSkeleton/2.add-header.tsx
- src/components/LoadingSkeletons/examples/SingleLineLoadingSkeleton/3.two-rows-three-columns.tsx
- src/index.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BWAP-718_Add_SingleLineLoadingSkeleton_to_Lucid)
> BWAP-718 Added SingleLineSkeleton

- docs/load-components.js
- src/components/LoadingSkeletons/SmallDataTableLoadingSkeleton.spec.tsx
- src/components/LoadingSkeletons/SmallDataTableLoadingSkeleton.tsx
- src/components/LoadingSkeletons/examples/SmallDataTableLoadingSkeleton/1.basic.tsx
- src/components/LoadingSkeletons/examples/SmallDataTableLoadingSkeleton/2.add-header.tsx
- src/components/LoadingSkeletons/examples/SmallDataTableLoadingSkeleton/3.two-rows-two-columns.tsx
- src/index.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BWAP-711_RebuildPR_Add_SmallDataTableLoadingSkeleton_to_Lucid)
> BWAP-711 Added SmallDataTableLoadingSkeleton

- src/components/DataTable/DataTable.tsx
- src/components/DataTable/__snapshots__/DataTable.spec.tsx.snap
- src/components/DataTable/examples/15.truncate-content.tsx
- src/components/Table/Table.less
- src/components/Table/Table.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-1069_1_add_truncating_ellipses_to_header_columns)
- [ x] Chrome
- [] Firefox
- [x ] Safari
- [x ] Unit tests written (`common` at minimum)
- [x ] PR has one of the `semver-` labels
> Bude 1069 1 add truncating ellipses to header columns

- src/components/DataTable/DataTable.spec.tsx
- src/components/DataTable/DataTable.tsx
> Exposing data table column width to child components

- CHANGELOG.md
- src/components/TextFieldValidated/TextFieldValidated.less
- src/components/TextFieldValidated/TextFieldValidated.tsx
- src/components/TextFieldValidated/__snapshots__/TextFieldValidated.spec.tsx.snap
- src/components/TextFieldValidated/examples/03.error_types.tsx
- src/components/Validation/Validation.less
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-1280/?path=/docs/controls-textfieldvalidated--basic)
> BUDE-1280: Rough draft of validated input warning and info

- src/components/DataTable/DataTable.tsx
In recent [PR for exposing a columns width](https://github.com/appnexus/lucid/pull/1235), unfortunately the change I made did not update width to child components on column resize. This change fixes that
> Small update to recent DataTable change

- .storybook/lucid-docs-addon/ChildComponents.tsx
- .storybook/lucid-docs-addon/PropTypes.tsx
- .storybook/lucid-docs-addon/register.tsx
- docs/index.stories.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/cxp-2041-update-primaryLight/?path=/docs/documentation-intro--page)
> Cxp 2149 bug react syntax highlighter paths

- docs/icons/load-icons.ts
- src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.less
- src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.spec.tsx
- src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.stories.tsx
- src/components/Icon/DoubleChevronIcon/DoubleChevronIcon.tsx
- src/components/Icon/DoubleChevronIcon/__snapshots__/DoubleChevronIcon.spec.tsx.snap
- src/components/Icon/Icon.tsx
- src/components/Icon/PinIcon/PinIcon.less
- src/components/Icon/PinIcon/PinIcon.spec.tsx
- src/components/Icon/PinIcon/PinIcon.stories.tsx
- src/components/Icon/PinIcon/PinIcon.tsx
- src/components/Icon/PinIcon/__snapshots__/PinIcon.spec.tsx.snap
- src/index.ts
- src/styles/components.less
- src/util/component-types.ts
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2163-Add-Icons-Lucid/?path=/docs/documentation-intro--page)
> chore: add double chevron and pin icons

- src/components/Tabs/Tabs.less
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/Update-Tabs-Hover/?path=/docs/navigation-tabs--title-as-prop)
* To account for the displacement of the content on hover, adding an initial margin bottom value to to be replaced on hover and if is active
> fix: update hover and active styling

- src/components/Banner/Banner.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/fix-banner-propTypes)
> make IBannerProps optional

- src/components/Collapsible/Collapsible.tsx
- src/components/Overlay/Overlay.tsx
- src/components/Portal/Portal.tsx
- src/components/SlidePanel/SlidePanel.tsx
- src/components/SplitHorizontal/SplitHorizontal.tsx
- src/components/StickySection/StickySection.tsx
- src/components/TextField/TextField.tsx
> Replaced Object.keys with lodash keys to fix propType checks in prod builds

- src/components/Table/Table.less
Border-color CSS should only specify color.
> fix typo in the border-color css declaration

- src/components/Panel/Panel.stories.tsx
- src/components/RadioButtonLabeled/RadioButtonLabeled.stories.tsx
- src/components/RadioGroup/RadioGroup.stories.tsx
Fixes Storybook linting warning:
`warning  Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name  storybook/no-redundant-story-name`
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/Fix-Storyboo-Named-Exports-Linting-Error)
https://docspot.adnxs.net/projects/lucid/Fix-Storyboo-Named-Exports-Linting-Error
> Remove Storybook named stories to fix a linting error

- src/components/Portal/Portal.spec.tsx
- src/components/Portal/Portal.tsx
This is about adding data-test-ids to portal so that we can use them in our cypress tests to verify the UI behaviour around the dialog and other UI Elements where portal is being used. 
I added className as data-test-id because it seems to be the best way, as if I used portalId, it was something autogenerated one which we can't use to test the behaviour.
> OE-975 : add data-test-id to lucid portals

- src/components/TextField/TextField.spec.tsx
- src/components/TextField/TextField.stories.tsx
- src/components/TextField/TextField.tsx
- src/components/TextField/TextFieldPlain.spec.tsx
- src/components/TextField/TextFieldPlain.tsx
- src/components/TextField/__snapshots__/TextField.spec.tsx.snap
- src/components/TextFieldValidated/TextFieldValidated.spec.tsx
- src/components/TextFieldValidated/TextFieldValidated.stories.tsx
- src/components/TextFieldValidated/TextFieldValidated.tsx
- src/components/TextFieldValidated/__snapshots__/TextFieldValidated.spec.tsx.snap
For TextField and TextFieldValidated:
Replaces deprecated omitProps method with an explicit list of omitted props.
Adds unit tests for the omitted props
Updates the stories to SB6
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2589-TextField-Validated-Fix-Props/?path=/docs/controls-textfield--basic)
TextField:
https://docspot.adnxs.net/projects/lucid/CXP-2589-TextField-Validated-Fix-Props/?path=/docs/controls-textfield--basic
TextFieldValidated:
https://docspot.adnxs.net/projects/lucid/CXP-2589-TextField-Validated-Fix-Props/?path=/docs/controls-textfieldvalidated--basic
> Cxp 2589 text field validated fix props

- src/components/SearchField/SearchField.spec.tsx
- src/components/SearchField/SearchField.stories.tsx
- src/components/SearchField/SearchField.tsx
- Replace omitProps with _.omit and explicit list of nonPassThroughs props for SearchField.
- Tidy up the SB6 stories.
- Add a unit test to ensure the props are removed. 
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2810-SearchField-Remove-omitProps/?path=/docs/controls-searchfield--basic)
SearchField Story:
https://docspot.adnxs.net/projects/lucid/CXP-2810-SearchField-Remove-omitProps/?path=/docs/controls-searchfield--basic
> Remove omitProps from SearchField and add unit tests for the nonPassThroughs

- src/components/Autocomplete/Autocomplete.stories.tsx
- src/components/ButtonGroup/ButtonGroup.spec.tsx
- src/components/ButtonGroup/ButtonGroup.stories.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
- src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.tsx.snap
- src/components/RadioButton/RadioButton.tsx
- src/components/RadioGroup/RadioGroup.spec.tsx
- src/components/RadioGroup/RadioGroup.stories.tsx
- src/components/RadioGroup/RadioGroup.tsx
- src/components/RadioGroup/__snapshots__/RadioGroup.spec.tsx.snap
- src/components/TextField/TextField.spec.tsx
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/CXP-2720-RadioGroup-ButtonGroup-Props)
RadioGroup
https://docspot.adnxs.net/projects/lucid/CXP-2720-RadioGroup-ButtonGroup-Props/?path=/docs/controls-radiogroup--stateful
ButtonGroup
https://docspot.adnxs.net/projects/lucid/CXP-2720-RadioGroup-ButtonGroup-Props/?path=/docs/controls-buttongroup--basic
> Cxp 2720 radio group button group props

- src/components/Tag/Tag.spec.tsx
- src/components/Tag/Tag.stories.tsx
- src/components/Tag/Tag.tsx
For the Tag component:
- Replaces omitProps method with _.omit and explicit list of props
- Adds unit tests to make sure correct props are being omitted or passed on
- Upgrades Tag stories to be functional and use controls
- Adds descriptions to the Tag stories
https://docspot.adnxs.net/projects/lucid/CXP-2588-Replace-omitProps-in-Tag/?path=/docs/communication-tag--basic
> Replace omitProps with omit add unit tests stories

- src/components/Expander/Expander.spec.tsx
- src/components/Expander/Expander.stories.tsx
- src/components/Expander/Expander.tsx
- src/components/Expander/__snapshots__/Expander.spec.tsx.snap
- src/components/ExpanderPanel/ExpanderPanel.spec.tsx
- src/components/ExpanderPanel/ExpanderPanel.stories.tsx
- src/components/ExpanderPanel/ExpanderPanel.tsx
- src/components/ExpanderPanel/__snapshots__/ExpanderPanel.spec.tsx.snap
Replace omitProps method with explicit list of omitted props `nonPassThroughs`
Write Unit test for omitted and included tests
Update Storybook to display SB6 options and use functional examples.
https://docspot.adnxs.net/projects/lucid/CXP-2565-Expander-ExpanderPanel-Replace-omitProps/?path=/docs/layout-expander--basic
https://docspot.adnxs.net/projects/lucid/CXP-2565-Expander-ExpanderPanel-Replace-omitProps/?path=/docs/layout-expanderpanel--basic
> Cxp 2565 Expander ExpanderPanel replace omit props

- src/components/Dialog/Dialog.spec.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/__snapshots__/Dialog.spec.tsx.snap
- src/components/Overlay/Overlay.tsx
For `Dialog` component:
Replace omitProps with omit and explicit list of props
Update Storybook basic story to SB6
Add a unit test to check for omitted and included props
https://docspot.adnxs.net/projects/lucid/CXP-2562-Replace-omitProps-Dialog/?path=/docs/layout-dialog--basic
> Replace omitProps in Dialog and update unit test and Storybook

- src/components/DataTable/DataTable.spec.tsx
- src/components/DataTable/DataTable.stories.tsx
- src/components/DataTable/DataTable.tsx
- Replace omitProps with _.omit for DataTable (in five places)
- add unit tests to ensure the correct props are being omitted and being passed through
- update Stories to Storybook 6 format
https://docspot.adnxs.net/projects/lucid/CXP-2560-DataTable-Replace-OmitProps/?path=/docs/table-datatable--basic
> Replace omitProps with _.omit, add unit tests and update Stories

- src/components/DropMenu/DropMenu.spec.tsx
- src/components/DropMenu/DropMenu.stories.tsx
- src/components/DropMenu/DropMenu.tsx
Add unit test for DropMenu props
https://docspot.adnxs.net/projects/lucid/CXP-2564-DropMenu-Replace-omitProps/?path=/docs/helpers-dropmenu--basic
> Add unit test for DropMenu props

- src/components/TextField/TextField.spec.tsx
- src/components/TextField/TextField.tsx
- src/components/TextFieldValidated/TextFieldValidated.spec.tsx
- src/components/TextFieldValidated/TextFieldValidated.stories.tsx
Fix error warning on ref special prop
Add some more test coverage to TextFieldValidated unit tests
https://docspot.adnxs.net/projects/lucid/CXP-2951-TextFieldValidated-Ref-Error/?path=/docs/controls-textfieldvalidated--basic
> Cxp 2951 text field validated ref error

- src/components/TextFieldValidated/TextFieldValidated.less
- src/components/TextFieldValidated/TextFieldValidated.spec.tsx
- src/components/TextFieldValidated/TextFieldValidated.stories.tsx
- src/components/TextFieldValidated/TextFieldValidated.tsx
- src/components/TextFieldValidated/__snapshots__/TextFieldValidated.spec.tsx.snap
(New PR since [last one](https://github.com/appnexus/lucid/pull/1270) is too out of date)
Update TextFieldValidated to accept a special prop with text and border color strings to style informational messages
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-1755/?path=/docs/controls-textfieldvalidated--basic)
> BUDE-1755/BUDE-1535: Add special prop to TextFieldValidated that allows custom error text and border color 

- src/components/PieChart/PieChart.spec.tsx
- src/components/PieChart/PieChart.stories.tsx
- src/components/PieChart/PieChart.tsx
- src/components/PieChart/__snapshots__/PieChart.spec.tsx.snap
- src/components/ToolTip/ToolTip.spec.tsx
- src/components/ToolTip/ToolTip.stories.tsx
- src/components/ToolTip/ToolTip.tsx
- ToolTip and Pie Chart replace omitProps with explicit list of props
- Add unit tests for omitted pass throughs
- Update Storybook stories
- Update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-2573-PieChart-replace-omitProps/?path=/docs/visualizations-piechart--basic
https://docspot.adnxs.net/projects/lucid/CXP-2573-PieChart-replace-omitProps/?path=/docs/communication-tooltip--basic
> Cxp 2573 pie chart and tool tip replace omit props

- src/components/Portal/Portal.spec.tsx
- src/components/Portal/Portal.stories.tsx
- src/components/Portal/Portal.tsx
- Add unit test for pass throughs
- Update stories to SB6 and functional comp
- Replace omitProps with explicit list of props
https://docspot.adnxs.net/projects/lucid/CXP-2575-Portal-Replace-omitProps/?path=/docs/utility-portal--basic
> Cxp 2575 Portal replace omit props

- src/components/Switch/Switch.spec.tsx
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Switch/__snapshots__/Switch.spec.tsx.snap
Description of changes to `Switch`:
* Add stateful Basic story 
* Replace omitProps with explicit list of props
* Update unit test
* Update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-Switch-SwitchLabeled-replace-omitProps/?path=/docs/controls-switch--basic
> Cxp switch switch labeled replace omit props

- src/components/SplitHorizontal/SplitHorizontal.spec.tsx
- src/components/SplitHorizontal/SplitHorizontal.stories.tsx
- src/components/SplitHorizontal/SplitHorizontal.tsx
- src/components/VerticalListMenu/VerticalListMenu.spec.tsx
- src/components/VerticalListMenu/VerticalListMenu.stories.tsx
- src/components/VerticalListMenu/VerticalListMenu.tsx
VerticalListMenu & Split Horizontal
replace omitProps with explicit list of props
https://docspot.adnxs.net/projects/lucid/CXP-2529-VerticalListMenu-replace-omitProps/?path=/docs/navigation-verticallistmenu--basic
https://docspot.adnxs.net/projects/lucid/CXP-2529-VerticalListMenu-replace-omitProps/?path=/docs/private-splithorizontal--default-split
> Cxp 2529 vertical list menu& splithorizontal replace omit props

- src/components/ScrollTable/ScrollTable.spec.tsx
- src/components/ScrollTable/ScrollTable.stories.tsx
- src/components/ScrollTable/ScrollTable.tsx
- src/components/ScrollTable/__snapshots__/ScrollTable.spec.tsx.snap
Description of changes to ScrollTable:
* Add unit tests for omitted props
* Update ScrollTable stories to use controls
* Replace omitProps with explicit list of propTypes
* Update snapshot for ScrollTable
https://docspot.adnxs.net/projects/lucid/CXP-2578-ScrollTable-fix-omitProps/?path=/docs/table-scrolltable--basic
> Cxp 2578 scroll table fix omit props

- src/components/SplitButton/SplitButton.spec.tsx
- src/components/SplitButton/SplitButton.stories.tsx
- src/components/SplitButton/SplitButton.tsx
- src/components/SplitButton/__snapshots__/SplitButton.spec.tsx.snap
[Add unit tests for omitted props]
[Update stories to SB6]
[Update snapshots]
[Replace omitProps with explicit list of props]
https://docspot.adnxs.net/projects/lucid/CXP-2581-SplitButton-replace-omitProps/?path=/docs/controls-splitbutton--basic
> Cxp 2581 split button replace omit props

- src/components/TextFieldValidated/TextFieldValidated.tsx
Just remove optional chaining that is preventing compilation in some apps
[link](https://docspot.adnxs.net/projects/lucid/BUDE-1755_2/?path=/docs/controls-textfieldvalidated--basic)
> BUDE-1755: Remove optional chaining due to compile issues

- src/components/SplitVertical/SplitVertical.spec.tsx
- src/components/SplitVertical/SplitVertical.stories.tsx
- src/components/SplitVertical/SplitVertical.tsx
* Add unit tests for pass throughs and propTypes
* Update Stories with SB6 controls and make them functional
* Replace omitProps with explicit list of props
https://docspot.adnxs.net/projects/lucid/CXP-2583-SplitVertical-fix-propTypes-passthroughs/?path=/docs/private-splitvertical--default-split
> Cxp 2583 split vertical fix prop types passthroughs

- src/components/Table/Table.spec.tsx
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/VerticalTabs/VerticalTabs.spec.tsx
- src/components/VerticalTabs/VerticalTabs.stories.tsx
- src/components/VerticalTabs/VerticalTabs.tsx
Description of changes for VerticalTabs and Table components:
* Add unit tests for prop types
* Update Stories with args and Story TS definition
* Replace omitProps with explicit list of props
https://docspot.adnxs.net/projects/lucid/CXP-2593-VerticalTabs-fix-omitProps/?path=/docs/navigation-verticaltabs--basic
https://docspot.adnxs.net/projects/lucid/CXP-2593-VerticalTabs-fix-omitProps/?path=/docs/table-table--basic
> Cxp 2593 vertical tabs & table fix omit props

- src/components/StickySection/StickySection.spec.tsx
- src/components/StickySection/StickySection.stories.tsx
- src/components/StickySection/StickySection.tsx
Description of changes for `StickySection`:
Replace omitProps by propTypes with an explicit list
Update Storybook story
Add unit test for omitted props.
https://docspot.adnxs.net/projects/lucid/CXP-2584-StickySection-replace-omitProps/?path=/docs/helpers-stickysection--with-lower-bound
> Cxp 2584 sticky section replace omit props

- src/components/LoadingMessage/LoadingMessage.spec.tsx
- src/components/LoadingMessage/LoadingMessage.stories.tsx
- src/components/LoadingMessage/LoadingMessage.tsx
- src/components/LoadingMessage/__snapshots__/LoadingMessage.spec.tsx.snap
- src/components/SidePanel/SidePanel.spec.tsx
- src/components/SidePanel/SidePanel.stories.tsx
- src/components/SidePanel/SidePanel.tsx
- src/components/SidePanel/__snapshots__/SidePanel.spec.tsx.snap
- src/styles/components.less
For LoadingMessage:
* replace omitProps with an explicit list of props.
* add Storybook story for LoadingMessage
* add unit test to ensure the correct props are being omitted and passed through to the underlying root element
https://docspot.adnxs.net/projects/lucid/CXP-2571-LoadingMessage-replace-omitProps/?path=/docs/loading-message-loadingmessage--basic
> Cxp 2571 loading message replace omit props

- src/components/SidePanel/SidePanel.spec.tsx
- src/components/SidePanel/SidePanel.stories.tsx
- src/components/SidePanel/SidePanel.tsx
- src/components/SidePanel/__snapshots__/SidePanel.spec.tsx.snap
Description of changes to `SidePanel`
- replace omitProps with explicit list of omitted props
- update Stories to SB6 with controls and functional components
- Add unit test coverage for passThroughs
https://docspot.adnxs.net/projects/lucid/CXP-2580-SidePanel-remove-omitProps/?path=/docs/layout-sidepanel--no-modal
> SidePanel replace omitProps, update Stories, add unit test coverage

- src/components/Resizer/Resizer.spec.tsx
- src/components/Resizer/Resizer.stories.tsx
- src/components/Resizer/Resizer.tsx
- src/util/component-types.ts
- Remove omitProps, 
- add unit test and 
- convert story to sb6 
https://docspot.adnxs.net/projects/lucid/CXP-2576-Replace-omitProps-Resizer/?path=/docs/utility-resizer--basic
> Remove omitProps, add unit test and convert story to sb6 for Resizer

- src/components/LineChart/LineChart.spec.tsx
- src/components/LineChart/LineChart.stories.tsx
- src/components/LineChart/LineChart.tsx
- src/components/LineChart/__snapshots__/LineChart.spec.tsx.snap
- src/components/SplitVertical/SplitVertical.spec.tsx
Description of changes to `LineChart`:
* Add unit test for pass throughs
* Add controls and type defs to Stories
* Replace omitProps method with list of props
* update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-2569-LineChart-replace-omitProps/?path=/docs/visualizations-linechart--basic
> Cxp 2569 line chart replace omit props

- src/components/InfiniteSlidePanel/InfiniteSlidePanel.spec.tsx
- src/components/InfiniteSlidePanel/InfiniteSlidePanel.stories.tsx
- src/components/InfiniteSlidePanel/InfiniteSlidePanel.tsx
- src/components/InfiniteSlidePanel/__snapshots__/InfiniteSlidePanel.spec.tsx.snap
- src/components/SplitVertical/SplitVertical.spec.tsx
Description of changes to <InfiniteSlidePanel />
* replace omitProps with explicit list of omitted props
* update snapshot
* add a unit test for the pass throughs
* add ts defs and activate SB6 controls for the Story and make it a functional component story
https://docspot.adnxs.net/projects/lucid/CXP-2568-InfiniteSidePanel-replace-omitProps/?path=/docs/private-infiniteslidepanel--dynamic-content
> Cxp 2568 infinite side panel replace omit props

- src/components/Validation/Validation.spec.tsx
- src/components/Validation/Validation.stories.tsx
- src/components/Validation/Validation.tsx
- src/components/Validation/__snapshots__/Validation.spec.tsx.snap
Description of changes to Validation:
- Add unit test for omitted props
- Fix import error in Validation story
- Revise omitted props for root div
- Update Validation snapshot
Storybook
https://docspot.adnxs.net/projects/lucid/CXP-2591-Validation-replace-omitProps/?path=/docs/helpers-validation--basic
> Cxp 2591 validation replace omit props

- src/components/PieChart/PieChart.stories.tsx
- src/components/Points/Points.spec.tsx
- src/components/Points/Points.stories.tsx
- src/components/Points/Points.tsx
Update Points stories to SB6 and replace deprecated omitProps method with explicit list of omitted props.
https://docspot.adnxs.net/projects/lucid/CXP-2574-Points-replace-omitProps/?path=/docs/visualizations-points--basic
> Cxp 2574 points replace omit props

- src/components/SlidePanel/SlidePanel.spec.tsx
- src/components/SlidePanel/SlidePanel.stories.tsx
- src/components/SlidePanel/SlidePanel.tsx
Replace omitProps with explicit list of props for SlidePanel
Add unit test for omitted props
Update Storybook to SB6 and functional stories
https://docspot.adnxs.net/projects/lucid/CXP-2970-SlidePanel-replace-omitProps/?path=/docs/private-slidepanel--looped-slides
- [x
] PR has one of the `semver-` labels
> Cxp 2970 slide panel replace omit props

- src/components/SidePanel/SidePanel.tsx
- src/components/SidePanel/__snapshots__/SidePanel.spec.tsx.snap
**Description of changes:**
Currently our SidePanel component has the following default props:
Width: 240px 
minWidth: -Infinity
maxWidth: Infinity
If teams don't update these values it can create instances where data layouts within the SidePanel fall apart. 
**Update the defaults to the following:**
Width: 500px
midWidth: 500px
maxWidth: 90% (Can we do percentages for this?)
Product teams should still be able to update these props to suite their particular content layout needs.
https://docspot.adnxs.net/projects/lucid/CXP-3031-update-default-props-sidepanel
- [x ] Chrome
- [x ] Firefox
- [x ] Two cxp team engineer approvals
- [x ] PR has one of the `semver-` labels
> Update the default values for the side panel

- src/components/SearchField/SearchField.tsx
- src/components/SearchableSelect/SearchableSelect.spec.tsx
- src/components/SearchableSelect/SearchableSelect.tsx
- src/components/TextField/TextField.tsx
- support autofocus onto TextField when SearchableSelect is opened
- add/extend existing `focus` methods to support optional `FocusOptions` parameter for `TextField` and `SearchField`  (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)
Link(s) to Storybook on docspot: https://docspot.adnxs.net/projects/lucid/CXP-3019-autofocus-onto-searchableselect-open/?path=/docs/controls-searchableselect--basic
> CXP-3019: SearchableSelect component autofocus to search field on open

- src/components/Autocomplete/Autocomplete.spec.tsx
- src/components/DraggableLineChart/DraggableLineChart.spec.tsx
- src/components/DraggableLineChart/DraggableLineChart.stories.tsx
- src/components/DraggableLineChart/DraggableLineChart.tsx
- src/components/DraggableLineChart/__snapshots__/DraggableLineChart.spec.tsx.snap
- src/components/DraggableLineChart/d3-helpers.ts
* Add unit test for pass throughs
* Convert SB Story to SB6 with controls
* Explicitly omit props and add className prop
* Update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-3054-DraggableLineChart-fix-propTypes/?path=/docs/visualizations-draggablelinechart--basic-draggable-line-chart
> Cxp 3054 draggable line chart fix prop types

- src/components/IconSelect/IconSelect.spec.tsx
- src/components/IconSelect/IconSelect.stories.tsx
- src/components/IconSelect/IconSelect.tsx
- src/components/IconSelect/__snapshots__/IconSelect.spec.tsx.snap
Description of changes to IconSelect:
* Add unit test for pass through
* Tidy up SB story
* Replace omitProps with list of omitted props
* Update snapshot
> Cxp 3056 icon select replace omit props

- src/components/Switch/Switch.tsx
- src/components/SwitchLabeled/SwitchLabeled.spec.tsx
- src/components/SwitchLabeled/SwitchLabeled.stories.tsx
- src/components/SwitchLabeled/SwitchLabeled.tsx
- src/components/SwitchLabeled/__snapshots__/SwitchLabeled.spec.tsx.snap
Description of changes to SwitchLabeled:
* Convert stories to SB6 functional stories
* Add unit tests for pass throughs
* Remove omitProps method that uses propType
* Update snapshots
https://docspot.adnxs.net/projects/lucid/CXP-3059-SwitchLabeled-omit-props/?path=/docs/controls-switchlabeled--basic
> Cxp 3059 switch labeled omit props

- src/components/Submarine/Submarine.spec.tsx
- src/components/Submarine/Submarine.stories.tsx
- src/components/Submarine/Submarine.tsx
- src/components/Submarine/__snapshots__/Submarine.spec.tsx.snap
- src/util/component-types.ts
Description of changes to `<Submarine />`:
* Upgrade to functional StoryBook Stories with type defs
* Add intelliSense to component-type functions
* Add unit tests for pass throughs
* Replace omitProps with explicit list of props
*Update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-2585-Submarine-fix-omitProps/?path=/docs/layout-submarine--basic
> Cxp 2585 Submarine fix omit props

- src/components/SearchableMultiSelect/SearchableMultiSelect.spec.tsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.stories.tsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
- src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.tsx.snap
Description of changes to SearchableMultiSelect:
* Update Stories to SB6 functional stories
* Add unit test for pass throughs
* Remove omitProps method
* Update snapshot
https://docspot.adnxs.net/projects/lucid/CXP-3057-SearchableMultiSelect-omitProps/?path=/docs/controls-searchablemultiselect--basic
> Cxp 3057 searchable multi select omit props

- src/components/DataTable/DataTable.tsx
- src/components/DateSelect/DateSelect.tsx
- src/components/DraggableLineChart/DraggableLineChart.tsx
- src/components/Expander/Expander.tsx
- src/components/ExpanderPanel/ExpanderPanel.tsx
- src/components/InfiniteSlidePanel/InfiniteSlidePanel.tsx
- src/components/PieChart/PieChart.tsx
- src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
- src/components/VerticalListMenu/VerticalListMenu.tsx
- src/util/component-types.spec.tsx
- src/util/component-types.ts
* Remove omitProps method orphans
* addSpecialOmittedProps to SearchableMultiSelect
* Unit test for addSpecialOmittedProps
* Deprecate omitProps, add addSpecialOmittedProps
* Remove omitProps from DateSelect
https://docspot.adnxs.net/projects/lucid/CXP-3062-Deprecate-omitProps-method/
> Cxp 3062 deprecate omitProps method

- src/components/Panel/Panel.stories.tsx
- src/components/Panel/__snapshots__/Panel.spec.tsx.snap
It should be 32px and have a margin of 15px on the right.
Link(s) to Storybook on docspot: https://docspot.adnxs.net/projects/lucid/CXP-3064-update-panel-icon-size
> Update the settings icon to reflect what we use in XDS.
