package.json
src/docs/index.jsx
src/docs/index.less

Fixes #36
- Included react-router for proper routing

Big refactor of docs page

---

src/components/Switch/Switch.spec.jsx

Following the approach I ended up using for the in-progress `RadioButton` component.

#20 -- Minor refactor of Switch component unit tests

---

src/components/Tabs/Tabs.less

Add a background color to Tabs

---

src/components/Button/Button.less
src/docs/containers/colors.jsx
src/styles/variables.less

* Add back missing styles for button
* Change default border to correct color
* Change the order border and background in color palette

Button styles broken #79

---

PULL_REQUEST_TEMPLATE.md

Add a PR template

---

src/util/component-definition.js
src/util/state-management.js

fix bug for child component props array elements various types.
address issues #87 and #88.

fix bugs state management props #87 and #88

---

src/components/Tabs/Tabs.jsx

Change stroke-width to strokeWidth

---

src/components/RadioButton/RadioButton.less

Adjusted the size and offset of the radio button container element.

#101 -- Radio button visual tweaks

---

src/components/ValidatedTextField/ValidatedTextField.less

#106 -- ValidatedTextField width to 100%

---

PULL_REQUEST_TEMPLATE.md
src/components/Checkbox/Checkbox.jsx
src/components/LabeledCheckbox/LabeledCheckbox.jsx
src/components/LabeledCheckbox/LabeledCheckbox.less
src/components/LabeledCheckbox/LabeledCheckbox.spec.jsx
src/components/LabeledCheckbox/examples/interactive.jsx
src/components/LabeledCheckbox/examples/label-as-child.jsx
src/components/LabeledCheckbox/examples/label-as-prop.jsx
src/components/LabeledCheckbox/examples/states.jsx
src/components/LabeledRadioButton/LabeledRadioButton.less
src/components/LabeledRadioButton/examples/interactive.jsx
src/components/LabeledRadioButton/examples/label-as-child.jsx
src/components/LabeledRadioButton/examples/label-as-prop.jsx
src/components/LabeledRadioButton/examples/states.jsx
src/components/RadioButton/RadioButton.jsx
src/components/TextField/TextField.jsx
src/index.js
src/styles/components.less

#104 -- Added LabeledCheckbox composite.

---

src/styles/mixins.less

Dan Hahn is looking into creating the zindex mixin to handle future cases.

#116: button bug quickfix

---

gulp/docs.js
src/docs/index.jsx

Add support for child component documentation and parsing

---

src/components/Autocomplete/Autocomplete.less

Make Autocomplete input style selector more specific.

---

src/components/Panel/Panel.jsx
src/components/Panel/Panel.less
src/components/Panel/Panel.spec.jsx
src/components/Panel/examples/no-padding-in-content.jsx

Panel fixes

---

src/components/Button/Button.jsx
src/components/Button/Button.less
src/components/Button/Button.spec.jsx
src/components/Button/examples/basic.jsx
src/components/Button/examples/danger.jsx
src/components/Button/examples/info.jsx
src/components/Button/examples/link.jsx
src/components/Button/examples/primary.jsx
src/components/Button/examples/success.jsx
src/components/Button/examples/warning.jsx
src/docs/index.jsx
src/docs/index.less
src/styles/mixins.less
src/styles/variables.less

Bugfix/#164 - round 2

---

package.json
src/util/state-management.js
src/util/state-management.spec.jsx

Fixes #181 performance issue caused by lodash 4.7.0

---

src/components/TextField/TextField.jsx

Add clarification to `onSubmit` for `TextField`

---

src/components/ScrollTable/ScrollTable.jsx
src/components/ScrollTable/ScrollTable.less
src/components/ScrollTable/ScrollTable.spec.jsx
src/components/ScrollTable/examples/1.standard.jsx
src/components/ScrollTable/examples/2.set-width-and-height.jsx
src/components/ScrollTable/examples/3.full-width.jsx
src/components/ScrollTable/examples/4.set-table-width.jsx
src/components/Table/Table.jsx
src/components/Table/Table.less
src/components/Table/Table.spec.jsx
src/index.js
src/styles/components.less
src/styles/variables.less

Component ScrollTable

---

src/components/DataTable/DataTable.jsx
src/components/DataTable/DataTable.spec.jsx
src/components/DataTable/examples/1.basic.jsx
src/components/DataTable/examples/2.column-groups-with-extra-space.jsx
src/components/DataTable/examples/3.selectable-and-navigable-rows.jsx
src/components/DataTable/examples/4.interactive-table.jsx
src/index.js

Component DataTable

---

src/components/Tabs/Tabs.jsx
src/components/Tabs/Tabs.spec.jsx

Change Tabs onSelect signature

---

src/components/Icon/ResizeIcon/ResizeIcon.jsx

fix ResizeIcon prop name

---

src/util/state-management.js
src/util/state-management.spec.jsx

fix safe merge function

---

src/components/ContextMenu/ContextMenu.jsx
src/components/ContextMenu/ContextMenu.spec.js
src/components/DropMenu/DropMenu.jsx
src/components/DropMenu/DropMenu.spec.jsx

remove autoflipping from ContextMenu

---

src/components/ButtonGroup/ButtonGroup.jsx
src/components/ButtonGroup/ButtonGroup.spec.jsx

ButtonGroup Button onClick bug

---

src/components/DataTable/DataTable.jsx
src/components/DataTable/DataTable.spec.jsx
src/components/DataTable/examples/5.disabled-rows.jsx

PPR-319 (issue #268): pass all data row props to the <Tr> (semver minor)

---

src/components/DataTable/examples/5.disabled-rows.jsx

fix missing comma

---

README.md

Our readme was a little out of date.

Update the readme for 1.0

---

src/components/Table/Table.less

- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~

Fix small typo in Table styles

---

src/components/ContextMenu/ContextMenu.jsx

don't align flyout when isExpanded is false

---

README.md

Although we aren't yet leveraging a lot of BrowserStack, I'm adding them to a new "Credits" section since they have already provided us with free services for the project.
#298

Add credits to README, fixes #298

---

src/components/Autocomplete/Autocomplete.less

fix disabled autocomplete cursor

---

src/util/state-management.js

incorporate props into hybrid component's initialState

---

src/styles/mixins.less

Fixes #355
`patch`: fixed small issue with the `:active` state on button like elements
- ~~Manually tested across supported browsers~~ just chrome

Fixes #355 by restoring a z-index

---

src/components/Tabs/Tabs.jsx

omitProps on passThroughs

---

CONTRIBUTING.md

`none`: updated `CONTRIBUTING.md` to have the latest practices.

Contributing guidline updates

---

src/components/Icon/MinimizeIcon/MinimizeIcon.jsx
src/components/Icon/MinimizeIcon/MinimizeIcon.less
src/components/Icon/MinimizeIcon/MinimizeIcon.spec.jsx
src/components/Icon/MinimizeIcon/examples/default.jsx
src/index.js

fixes #379 
http://docspot.devnxs.net/projects/lucid/379-minimize-icon/#/components/MinimizeIcon

Adds MinimizeIcon

---

src/components/Icon/WarningIcon/WarningIcon.jsx
src/components/Icon/WarningIcon/WarningIcon.less
src/docs/containers/icons.jsx
src/docs/containers/icons.less
src/docs/index.jsx
src/docs/index.less

fixes #341 
- ~~Manually tested across supported browsers
- ~~[ ] PR has one of the `semver-` labels~~
http://docspot.devnxs.net/projects/lucid/341-icons-page/#/icons

add Icons page

---

src/components/Accordion/Accordion.jsx
src/components/ButtonGroup/ButtonGroup.jsx
src/components/ButtonGroup/ButtonGroup.spec.jsx
src/components/ContextMenu/ContextMenu.jsx
src/components/ExpanderPanel/ExpanderPanel.jsx
src/components/Grid/Grid.jsx
src/components/Icon/TableGearIcon/TableGearIcon.jsx
src/components/RadioGroup/RadioGroup.jsx
src/components/Tabs/Tabs.spec.jsx
src/components/TextFieldValidated/TextFieldValidated.jsx
src/components/ToolTip/ToolTip.jsx
src/components/VerticalListMenu/VerticalListMenu.jsx
src/util/generic-tests.jsx

384 prop names prop types

---

src/components/Validation/Validation.jsx
src/components/Validation/Validation.spec.jsx

Fixes #419 
- ~~Firefox~~
- ~~Safari~~

Fixes #419 by removing `null` default prop

---

src/components/Sidebar/Sidebar.less
src/components/Sidebar/Sidebar.spec.jsx
src/components/SplitHorizontal/SplitHorizontal.jsx
src/components/SplitHorizontal/SplitHorizontal.spec.jsx
src/components/SplitVertical/SplitVertical.jsx
src/components/SplitVertical/SplitVertical.less
src/components/SplitVertical/SplitVertical.spec.jsx
src/components/SplitVertical/examples/8.handle-resize.jsx
src/constants/motion-spring.js

react-motion animation for Sidebar

---

src/components/Tabs/Tabs.less

multiline tab color update

---

karma.conf.js
src/components/Sidebar/Sidebar.spec.jsx
src/components/SplitHorizontal/SplitHorizontal.spec.jsx
src/components/SplitVertical/SplitVertical.spec.jsx
src/components/TextField/TextField.spec.jsx
src/components/ToolTip/ToolTip.spec.jsx
tests/constants.js

Increasing async test timeouts

---

CONTRIBUTING.md
src/util/describe-with-dom.js

Removes describeWithDOM

---

src/components/SplitHorizontal/SplitHorizontal.jsx

Adds styles to fix scrolling behavior with submarine nested in sidebar

---

src/components/LoadingIndicator/LoadingIndicator.jsx
src/components/LoadingIndicator/LoadingIndicator.less
src/components/LoadingIndicator/LoadingIndicator.spec.jsx
src/components/LoadingIndicator/examples/1.interactive.jsx
src/components/LoadingIndicator/examples/6.light-overlay.jsx
src/styles/variables.less

Adds a new `overlayKind` prop to LoadingIndicator.

---

karma.conf.js

Fixes #505 
- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~

Exclude tests with '[mostly stable]' in the title.

---

src/styles/mixins.less

Adds -moz prefix for Firefox specific aliasing issue

---

src/index.js
src/util/state-management.js

- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~

Exports logger from Lucid, fixes a small typo.

---

src/components/Collapsible/Collapsible.jsx

This Might help prevent issue #515 but should be included in the code regardless.
- ~~Chrome~~
- ~~Firefox~~
- ~~Safari~~

Only hide content if collapsible is collapsed .

---

CONTRIBUTING.md

Update contrib with the latest deets

---

src/components/Icon/EqualsIcon/EqualsIcon.jsx
src/components/Icon/EqualsIcon/EqualsIcon.less
src/components/Icon/EqualsIcon/EqualsIcon.spec.jsx
src/components/Icon/EqualsIcon/examples/default.jsx
src/index.js

Add 'equals' icon

---

src/components/SingleSelect/SingleSelect.jsx

Updates function signature docs for `onSelect`.

---

package.json
src/components/SearchableSelect/SearchableSelect.reducers.js
src/components/Table/Table.jsx

- ~~[x] Chrome~~
- ~~[x] Firefox~~
- ~~[x] Safari~~
- ~~[x] IE11 (Win 7)~~
- ~~[x] Edge (Win 10)~~
- ~~[x] Unit tests written (`common` at minimum)~~
- ~~[x] One core team UX approval~~

Fixes lint errors, adds lint to test script

---

src/components/Icon/AsteriskIcon/AsteriskIcon.jsx
src/components/Icon/AsteriskIcon/AsteriskIcon.spec.jsx
src/components/Icon/AsteriskIcon/examples/default.jsx
src/index.js

Add AsteriskIcon component

---

src/components/DataTable/examples/7.empty-with-custom-title-and-body.jsx
src/components/DataTable/examples/8.empty-with-image.jsx

Fixes broken examples.

---

src/components/Collapsible/Collapsible.jsx

Uses omitProps to prevent invalid passThroughs.

---

src/components/EmptyStateWrapper/EmptyStateWrapper.jsx
src/components/EmptyStateWrapper/EmptyStateWrapper.spec.jsx

Spreads props through EmptyStateWrapper.

---

src/components/Validation/Validation.jsx

apply custom className to `Validation.Error`

---

.gitignore
.npmignore

for context: https://github.com/yarnpkg/yarn/issues/838#issuecomment-253362537

Ignore yarn.lock

---

README.md

Fixed syntax error in Readme #607

---

src/docs/index.jsx
src/docs/util.js

Fix docs page

---

src/components/SplitVertical/SplitVertical.jsx
src/components/SplitVertical/SplitVertical.less
src/components/SplitVertical/SplitVertical.spec.jsx
src/components/SplitVertical/examples/9.no-resize.jsx

add isResizeable prop to SplitVertical

---

src/components/Panel/Panel.jsx
src/components/Panel/Panel.less
src/components/Panel/Panel.spec.jsx
src/components/Panel/examples/no-margins.jsx

Panel has margin

---

src/components/Checkbox/Checkbox.spec.jsx
src/components/DragCaptureZone/DragCaptureZone.spec.jsx
src/components/RadioButton/RadioButton.spec.jsx
src/components/RadioGroup/RadioGroup.spec.jsx
src/components/Switch/Switch.spec.jsx

Remove use of 'react/lib/SyntheticEvent'

---

.eslintrc
src/components/Accordion/Accordion.spec.jsx
src/components/Button/Button.spec.jsx
src/components/Tabs/Tabs.spec.jsx
src/components/VerticalTabs/VerticalTabs.spec.jsx
src/util/dom-helpers.js
src/util/generic-tests.jsx
src/util/state-management.js
src/util/state-management.spec.jsx

Added `prefer-const` lint rule and fixed const issues

---

.eslintrc
gulp/docs.js
src/components/Accordion/Accordion.reducers.js
src/components/Bars/Bars.jsx
src/components/ContextMenu/examples/3.menu-bar.jsx
src/components/DropMenu/DropMenu.jsx
src/components/ExpanderPanel/ExpanderPanel.jsx
src/components/Paginator/Paginator.spec.jsx
src/components/Sidebar/Sidebar.jsx
src/components/Sidebar/examples/10.nested-submarine.jsx
src/components/SingleSelect/examples/08.rich-content.jsx
src/components/SingleSelect/examples/09.no-selection-highlighting.jsx
src/components/SingleSelect/examples/10.array-options.jsx
src/components/SingleSelect/examples/11.stateless.jsx
src/components/SplitHorizontal/SplitHorizontal.jsx
src/components/SplitVertical/SplitVertical.jsx
src/components/Table/Table.jsx
src/docs/index.jsx
src/util/dom-helpers.js
src/util/state-management.js
webpack.config.js

Added paren and spacing lint rules with fixes

---

.eslintrc
src/components/Autocomplete/Autocomplete.reducers.spec.js
src/components/BarChart/BarChart.spec.jsx
src/components/BarChart/examples/03.grouped.jsx
src/components/BarChart/examples/04.grouped-with-legend.jsx
src/components/BarChart/examples/06.all-the-things.jsx
src/components/Bars/Bars.spec.jsx
src/components/Bars/examples/basic.jsx
src/components/Bars/examples/custom-colors.jsx
src/components/Lines/Lines.spec.jsx
src/components/Lines/examples/custom-colors.jsx
src/components/PieChart/PieChart.spec.jsx
src/components/PieChart/examples/1.basic.jsx
src/components/PieChart/examples/2.basic-donuts.jsx
src/components/PieChart/examples/4.color-map.jsx
src/components/PieChart/examples/5.percents.jsx
src/components/PieChart/examples/6.small-with-no-stroke-or-hover.jsx
src/components/Points/Points.spec.jsx
src/components/Points/examples/basic.jsx
src/components/Points/examples/custom-colors.jsx
src/components/ScrollTable/ScrollTable.spec.jsx
src/components/ToolTip/ToolTip.spec.jsx
src/components/VerticalListMenu/VerticalListMenu.reducers.spec.js
src/util/chart-helpers.spec.js
src/util/formatters.spec.js
src/util/generic-tests.jsx

http://eslint.org/docs/rules/comma-spacing

Added `comma-spacing` lint rule with fixes

---

src/util/redux.js

- ~~[ ] PR has one of the `semver-` labels~~

add dev-time redux-util helpers

---

src/components/ContextMenu/__snapshots__/ContextMenu.spec.jsx.snap
src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
src/util/component-types.js
src/util/component-types.spec.js

make `initialState` a first class property for `createClass`

---

src/components/SearchField/SearchField.jsx
src/components/SearchField/SearchField.spec.jsx
src/components/SearchField/__snapshots__/SearchField.spec.jsx.snap
src/components/SearchField/examples/9.debounced.jsx
src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.jsx.snap

expose `onChangeDebounced` for `SearchField`

---

src/util/redux.js

add helpful warnings for common errors with `getReduxPrimitives`

---

package.json
src/util/generic-tests.jsx

Upgrades Jest and cleans up some outdated devDeps

---

src/components/ExpanderPanel/ExpanderPanel.less

Increased Specificity for overwriting Panel styles to remove padding.

---

package.json

Runs lint and unit tests prior to pushing. Can be bypassed with `git push -n (or --no-verify)`
- ~~~Manually tested across supported browsers~~~
- ~~~Unit tests written (`common` at minimum)~~~

Added pre-push

---

src/components/Grid/Grid.jsx

Fixes small typo in docs for Grid

---

src/components/Tabs/Tabs.jsx
src/components/Tabs/Tabs.less

Fix Tabs IE Edge bug

---

src/components/Resizer/__snapshots__/Resizer.spec.jsx.snap
src/components/Sidebar/__snapshots__/Sidebar.spec.jsx.snap

fixes enzyme-to-json dep and related snapshots

---

src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
src/components/SearchableMultiSelect/examples/02.props.jsx
src/components/SearchableMultiSelect/examples/03.asynchronous.jsx

Added `hasSelections` prop to `SearchableMultiSelect`

---

package.json
src/components/Banner/Banner.jsx
src/components/Banner/__snapshots__/Banner.spec.jsx.snap
src/components/Expander/Expander.jsx
src/components/Expander/Expander.spec.jsx
src/components/Expander/__snapshots__/Expander.spec.jsx.snap
src/components/Overlay/Overlay.jsx
src/components/Overlay/Overlay.spec.jsx
src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
src/components/OverlayWrapper/OverlayWrapper.jsx
src/components/OverlayWrapper/__snapshots__/OverlayWrapper.spec.jsx.snap
src/components/SwitchLabeled/SwitchLabeled.jsx
src/components/SwitchLabeled/SwitchLabeled.spec.jsx
src/components/SwitchLabeled/__snapshots__/SwitchLabeled.spec.jsx.snap
yarn.lock

react-addons-css-transision-group -> react-transistion-group

---

src/components/Checkbox/Checkbox.less

Checkbox hide overflow content

---

package.json
src/components/DateSelect/DateSelect.jsx
src/docs/index.jsx
yarn.lock

Prop types

---

src/components/Collapsible/Collapsible.jsx

~- [ ] Unit tests written (`common` at minimum)~
~- [ ] One core team UX approval~

ANXR-897: gets rid of isMounted

---

src/components/Submarine/Submarine.jsx
src/components/Submarine/Submarine.less
src/components/Submarine/examples/10.hidden-bar.jsx
src/components/Submarine/examples/11-title-shown-collapsed.jsx

Demo: http://docspot.devnxs.net/projects/lucid/ANXR-909

ANXR-909: props to hide submarine & to show title when collapsed

---

src/components/Banner/Banner.less
src/components/Banner/__snapshots__/Banner.spec.jsx.snap
src/components/Banner/examples/stateful.jsx
src/components/Banner/examples/stateless.jsx

794 change banner colors to Light and add spaces between examples

---

src/components/RadioGroup/RadioGroup.jsx
src/components/RadioGroup/RadioGroup.spec.jsx
src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
src/components/RadioGroup/examples/is-disabled.jsx

Add radiogroup isDisabled prop

---

src/components/SingleSelect/SingleSelect.less

Add primary button gradients to singleselect

---

src/components/Sidebar/Sidebar.less
src/components/Table/Table.less

fixes 800 and 802

---

src/components/Breadcrumb/__snapshots__/Breadcrumb.spec.jsx.snap
src/components/Icon/SeparatorIcon/SeparatorIcon.jsx
src/components/Icon/SeparatorIcon/__snapshots__/SeparatorIcon.spec.jsx.snap

Updated svg for issue 781

---

src/components/DataTable/DataTable.jsx
src/components/DataTable/DataTable.spec.jsx
src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
src/components/DataTable/examples/07.empty-with-custom-title-and-body.jsx

Anxr 824 - Render minRows filler rows when data is empty

---

src/components/SplitHorizontal/SplitHorizontal.jsx
src/components/SplitHorizontal/__snapshots__/SplitHorizontal.spec.jsx.snap

This fixed the issue I was experiencing from #806 when I tested it locally.
I only tested Chrome -- it's out of my hands at this point. ✌️

Initializes state for isExpanded and isAnimated from props.

---

src/components/Button/Button.less

fixes #822 
http://docspot.devnxs.net/projects/lucid/922-invisible-button/#/components/Button

Button: fix type=link styles

---

package.json
src/components/Button/__snapshots__/Button.spec.jsx.snap
src/components/Button/examples/basic.jsx
src/components/Button/examples/danger.jsx
src/components/Button/examples/info.jsx
src/components/Button/examples/link.jsx
src/components/Button/examples/primary.jsx
src/components/Button/examples/success.jsx
src/components/Button/examples/warning.jsx
src/docs/index.less

Demo of it working now on the ANXR docs page
http://docspot.devnxs.net/projects/anx-react/test-830/#/components/Button

830: Fix button example styling

---

src/components/Tabs/Tabs.jsx
src/components/Tabs/Tabs.less
src/components/Tabs/__snapshots__/Tabs.spec.jsx.snap
src/components/Tabs/examples/8-navigation-progression-tabs.jsx

- [x ] Chrome
- [x ] Unit tests written (`common` at minimum)
- [x ] PR has one of the `semver-` labels
- [x ] One core team UX approval

Fixes #831 by correcting progressive tab style bug.

---

src/components/Tabs/Tabs.jsx

fix prop warning

---

src/components/Icon/FolderIcon/FolderIcon.jsx
src/components/Icon/FolderIcon/FolderIcon.spec.jsx
src/components/Icon/FolderIcon/__snapshots__/FolderIcon.spec.jsx.snap
src/components/Icon/FolderIcon/examples/1.default.jsx
src/components/Icon/FolderIcon/examples/2.clickable.jsx
src/components/Icon/FolderIcon/examples/3.disabled.jsx
src/index.js

fixes #758 
http://docspot.devnxs.net/projects/lucid/758-folder-icon/#/components/FolderIcon

add FolderIcon

---

src/components/DropMenu/DropMenu.jsx
src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
src/components/SearchableMultiSelect/SearchableMultiSelect.less
src/components/SearchableMultiSelect/SearchableMultiSelect.spec.jsx
src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.jsx.snap
src/components/SearchableMultiSelect/examples/04.grouped-options.jsx
src/components/SearchableSelect/SearchableSelect.jsx

fixes #866 
http://docspot.devnxs.net/projects/lucid/856-searchable-multiselect-checkbox-labeled/#/components/SearchableMultiSelect

SearchableMultiSelect: use CheckboxLabeled

---

src/components/SearchableSelect/SearchableSelect.jsx

fix SearchableSelect regresssion

---

high-level-feedback.md
src/components/IconBox/IconBox.jsx
src/components/IconGroup/IconGroup.jsx
src/components/IconSelect/examples/1.select-one-icon.jsx
src/components/IconSelect/examples/2.select-multiple-icons.jsx
src/components/IconSelect/examples/3.partially-select-icons.jsx

This is feedback for PR #873
I added notes for things that I thought about after spending some time trying trying to simplify the component API.
I also added 3 examples of a suggested component API that handles the 3 main use cases: selecting one icon, selecting many icons, partial selection of icons.

IconGroup Feedback and notes

---

src/components/LineChart/LineChart.jsx

LineChart: fix performance issue of reduntant state changes

---

gulp/docs.js
gulpfile.js
package.json
src/util/component-types.js
yarn.lock

Add gulp task to generate docgen json and publish it in dist

Publish docgen json

---

package.json
src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
src/components/BarChart/examples/13.many-bars.jsx
src/components/Bars/Bars.jsx
src/components/Bars/Bars.spec.jsx
src/components/Bars/__snapshots__/Bars.spec.jsx.snap
yarn.lock

optimize performance of bar charts

---

src/components/Icon/HelpIcon/HelpIcon.less

lucid-905: Make helpicon darker, change hover color as well.

---

.storybook/lucid-docs-addon/ExampleCode.js
.storybook/lucid-docs-addon/index.js
.storybook/lucid-docs-addon/register.js
.storybook/manager-head.html
.storybook/preview-head.html
docs/index.stories.js
docs/intro.md
src/components/Button/Button.jsx
src/components/ContextMenu/ContextMenu.jsx
src/components/Icon/LoadingIcon/LoadingIcon.jsx
src/components/Paginator/Paginator.jsx
src/components/SearchableSelect/SearchableSelect.jsx
src/components/SingleSelect/SingleSelect.jsx
src/components/SplitButton/SplitButton.jsx
src/components/ToolTip/ToolTip.jsx

Docs fix descriptions, bugs, and feedback

---

docs/index.stories.js

http://docspot.devnxs.net/projects/lucid/docs-component-categories/?selectedKind=Categories&selectedStory=Controls&full=0&addons=0

Add stories for component categories to docs

---

.storybook/manager-head.html
.travis.yml
docs/public/lucid/lucid-icon.png
gulp/docs.js
gulpfile.js
package.json
scripts/upload-docs-build-gh.sh

Tell travis to push docs after deploy, and set icon for docs page

Reorder docs deploy

---

src/components/AxisLabel/AxisLabel.less
src/components/Bar/Bar.less
src/components/Line/Line.less
src/components/Point/Point.less
src/components/VerticalListMenu/VerticalListMenu.less
src/docs/containers/color-palette.less
src/styles/mixins.less

- ~~Unit tests written (`common` at minimum)~~ I did diff the old and new css

Fixes #915 by removing recursion from less files

---

package.json

Only include src/components and src/utils in coverage report

Clean up jest coverage report

---

scripts/create-component-dev.sh
scripts/create-component-docs.sh
scripts/create-component-source.sh

Add some convenience scripts to quickly get started:
- `scripts/create-component-source.sh MyComponent` - create files for new compoennt
- `scripts/create-component-dev.sh MyComponent` - create storybook story for `npm run dev`
- `scripts/create-component-docs.sh MyComponent` - create component example for `npm run docs`
```
➜  lucid git:(master) ✗ ./scripts/create-component-source.sh Underline
Scaffolding new source code for new component: 'Underline'
Created ./src/components/Underline/Underline.jsx
Created ./src/components/Underline/Underline.spec.jsx
Created ./src/components/Underline/Underline.less
Make sure to export 'Underline' in 'src/index.js' and import 'Underline.less' in 'src/styles/components.less'!
Created new component: 'Underline'
➜  lucid git:(master) ✗ …
```

Add some convenience scripts to quickly get started

---

package.json

remove `browser` field from `package.json`

---

src/components/Checkbox/Checkbox.jsx
src/components/Checkbox/__snapshots__/Checkbox.spec.jsx.snap
src/components/Checkbox/examples/interactive.jsx

use `title` on the wrapper element so that a tooltip can be shown on hover.

add title to checkbox

---

src/components/Dialog/Dialog.jsx
src/components/Dialog/Dialog.less
src/components/Dialog/__snapshots__/Dialog.spec.jsx.snap
src/components/Dialog/examples/6.no-gutters.jsx

fixes #523 by changing the styles

---

src/components/Banner/Banner.jsx
src/components/Banner/Banner.less
src/components/Icon/Icon.jsx

fixes #741 by adding onSelect to Icon

---

src/components/Tabs/Tabs.less

Fixes #942 by changing Nav Tab font size

---

package.json

Mark the library are "pure" for webpack tree shaking

---

package-lock.json
src/components/Banner/__snapshots__/Banner.spec.jsx.snap
src/components/Icon/CrossIcon/CrossIcon.jsx
src/components/Icon/CrossIcon/__snapshots__/CrossIcon.spec.jsx.snap
src/components/Icon/CrossIcon/examples/1.default.jsx
src/components/Icon/CrossIcon/examples/2.clickable.jsx
src/components/Icon/CrossIcon/examples/3.disabled.jsx
src/components/Icon/Icon.jsx
src/components/Selection/__snapshots__/Selection.spec.jsx.snap
src/components/SidePanel/SidePanel.jsx
src/components/SidePanel/SidePanel.less
src/components/SidePanel/__snapshots__/SidePanel.spec.jsx.snap
src/components/Tag/__snapshots__/Tag.spec.jsx.snap
src/components/ToolTip/__snapshots__/ToolTip.spec.jsx.snap

#974, #968 - Larger Icon option and larger close button on the SidePanel header

---

src/components/Expander/Expander.jsx

the code that depended on this labelKey was removed by #988

Remove unused labelKey on Expander

---

src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
src/components/SearchableSingleSelect/examples/05.selected-option.jsx

SearchableSingleSelect - Render selected option's Selected prop if applicable

---

src/components/CalendarMonth/CalendarMonth.less
src/components/DropMenu/DropMenu.less
src/components/EmptyStateWrapper/EmptyStateWrapper.less
src/components/Expander/Expander.jsx
src/components/Expander/Expander.less
src/components/Expander/__snapshots__/Expander.spec.jsx.snap
src/components/Expander/examples/5.highlighted.jsx
src/components/ExpanderPanel/ExpanderPanel.less
src/components/ProgressBar/ProgressBar.less
src/components/SidePanel/SidePanel.less

misc styling tweaks per ux feedback

---

src/components/SingleSelect/SingleSelect.less
src/components/SingleSelect/__snapshots__/SingleSelect.spec.jsx.snap
src/components/SingleSelect/examples/13.invisible-and-disabled.jsx

fix some hardcoded white values in invisible singleselects

---

src/components/ToolTip/ToolTip.less

ToolTip: styling links like in Banner

---

docs/load-icons.js
package-lock.json
src/components/Icon/DotsIcon/DotsIcon.jsx
src/components/Icon/DotsIcon/DotsIcon.less
src/components/Icon/DotsIcon/DotsIcon.spec.jsx
src/components/Icon/DotsIcon/__snapshots__/DotsIcon.spec.jsx.snap
src/components/Icon/DotsIcon/examples/1.default.jsx
src/index.js
src/styles/components.less

added DotsIcon

---

src/components/SidePanel/SidePanel.less

update sidepanel shadow per ux

---

docs/color-palette.jsx
docs/color-palette.less
src/components/AxisLabel/AxisLabel.less
src/components/Bar/Bar.less
src/components/Bar/__snapshots__/Bar.spec.jsx.snap
src/components/Bar/examples/regular-colors.jsx
src/components/BarChart/BarChart.jsx
src/components/BarChart/__snapshots__/BarChart.spec.jsx.snap
src/components/BarChart/examples/04.grouped-with-legend.jsx
src/components/Bars/Bars.jsx
src/components/Legend/__snapshots__/Legend.spec.jsx.snap
src/components/Legend/examples/basic.jsx
src/components/Line/Line.less
src/components/Line/__snapshots__/Line.spec.jsx.snap
src/components/Line/examples/basic.jsx
src/components/LineChart/LineChart.jsx
src/components/LineChart/__snapshots__/LineChart.spec.jsx.snap
src/components/Lines/Lines.jsx
src/components/LoadingIndicator/__snapshots__/LoadingIndicator.spec.jsx.snap
src/components/OverlayWrapper/__snapshots__/OverlayWrapper.spec.jsx.snap
src/components/PieChart/PieChart.jsx
src/components/PieChart/examples/3.legend.jsx
src/components/Point/Point.less
src/components/Point/__snapshots__/Point.spec.jsx.snap
src/components/Point/examples/basic.jsx
src/components/Point/examples/big-with-stroke.jsx
src/components/Points/Points.jsx
src/components/VerticalTabs/__snapshots__/VerticalTabs.spec.jsx.snap
src/constants/charts.js
src/styles/variables.less

Chart color rebrand

---

src/components/DataTable/DataTable.jsx
src/components/DataTable/DataTable.spec.jsx
src/components/DataTable/__snapshots__/DataTable.spec.jsx.snap
src/components/DataTable/examples/12.resizable-fixed-headers-table.jsx
src/components/Table/Table.jsx

pass field value to Column instead of Th

---

src/components/Tabs/Tabs.less

update active multi line tab styling

---

src/components/DataTable/DataTable.jsx
src/components/Table/Table.jsx

Table Th Resizer - use omitProps & read field prop in handleResize callback

---

package-lock.json
package.json
src/components/Autocomplete/Autocomplete.jsx
src/components/Collapsible/Collapsible.spec.jsx
src/components/ContextMenu/__snapshots__/ContextMenu.spec.jsx.snap
src/components/DataTable/DataTable.spec.jsx
src/components/DropMenu/DropMenu.jsx
src/components/DropMenu/__snapshots__/DropMenu.spec.jsx.snap
src/components/Icon/LoadingIcon/LoadingIcon.jsx
src/components/Overlay/__snapshots__/Overlay.spec.jsx.snap
src/components/Paginator/Paginator.jsx
src/components/PieChart/PieChart.jsx
src/components/RadioGroup/__snapshots__/RadioGroup.spec.jsx.snap
src/components/SearchableMultiSelect/SearchableMultiSelect.jsx
src/components/SearchableSelect/SearchableSelect.jsx
src/components/SearchableSingleSelect/SearchableSingleSelect.jsx
src/components/SingleSelect/SingleSelect.jsx
src/components/SplitButton/SplitButton.jsx
src/components/TextFieldValidated/TextFieldValidated.jsx
src/components/VerticalListMenu/VerticalListMenu.jsx
src/util/component-types.js
src/util/component-types.spec.js
src/util/state-management.js

Remove getDefaultProps

---

src/components/Table/Table.less

adjust table header's border and style behavior

---

src/components/Button/Button.less

fix hover/active/focus background styling for button links

---

.codesandbox/ci.json

sorry, this fixes the json syntax for the codesandbox config

fix codesandbox ci syntax

---

.codesandbox/ci.json

add build command for codesandbox to build the package

add build command for codesandbox

---

src/components/Expander/Expander.less

centering chevron icon in button

---

src/util/component-types.ts

benefits:
- `this.props` hints in the render function
- enforce that `propTypes` on the definition has prop-type descriptions
note: tests will break with just this change
when `propTypes` is missing something from the props interface:

[proposal] enforce propType descriptions and allow passing a Generic to `createClass`

---

.storybook/lucid-docs-addon/register.js

Fix for users of older versions of storybook

---

examples/basic-app/src/index.tsx

update import of css in example-app
recreated https://github.com/appnexus/lucid/pull/1100 to use a `appnexus/lucid` branch

import css for example app

---

src/components/Legend/Legend.tsx
src/components/VerticalListMenu/VerticalListMenu.tsx

(Minor patch to) ts-convert Legend CXP-881

---

PULL_REQUEST_TEMPLATE.md

Update Pull Request Template

---

src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
src/components/SearchableMultiSelect/examples/06.select-all.tsx

I have added the option for a custom select all text.
https://docspot.adnxs.net/projects/lucid/BPAD-680

BPAD-680: Adding in custom select all text as an option

---

src/components/RadioButtonLabeled/RadioButtonLabeled.tsx
src/components/RadioGroup/RadioGroup.tsx
src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
src/components/SearchableSelect/SearchableSelect.tsx
src/components/SearchableSingleSelect/SearchableSingleSelect.tsx

Storybook can be viewed [here]()

Bug/release fixes for Lucid release

---

CHANGELOG.md
src/components/Autocomplete/Autocomplete.jsx
src/components/CalendarMonth/examples/6.show-cursor.jsx
src/components/Collapsible/Collapsible.tsx
src/components/ContextMenu/ContextMenu.tsx
src/components/DropMenu/DropMenu.tsx
src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
src/components/SearchableSelect/SearchableSelect.tsx
src/components/SearchableSingleSelect/SearchableSingleSelect.tsx
src/components/SingleSelect/SingleSelect.tsx
src/components/SplitHorizontal/SplitHorizontal.tsx
src/components/SplitVertical/SplitVertical.tsx
src/components/SwitchLabeled/SwitchLabeled.jsx
src/components/Table/Table.jsx
src/components/TextField/TextField.tsx
src/util/state-management.ts

There are no visual changes. This is simple addressing warnings that all consumers of this repo are seeing in the console. Replace deprecated lifecycles with the new keys to be clear they are deprecated and unsafe. We will need to come back and replace with hooks but for now this will address the warnings.
https://reactjs.org/docs/react-component.html
- [ x] Chrome
- [ x] Firefox
- [ x] Safari
- [NA ] One core team UX approval

Bude 25 lance part 3

---

CHANGELOG.md
README.md
RELEASING.md

revised Releasing.md instructions

---

CHANGELOG.md
RELEASING.md

Fix some errors in the RELEASING.md docs and improve the process a bit.

correct some of the releasing steps

---

src/components/SidePanel/SidePanel.tsx

Deal 1429 side panel improvement

---

src/components/DraggableLineChart/DraggableLineChartD3.ts

BUDE-811: Update color of point in DraggableLineChart

---

.stylelintrc
src/components/DraggableLineChart/DraggableLineChart.less
src/components/DraggableLineChart/DraggableLineChart.tsx
src/components/DraggableLineChart/examples/02.ExampleWithExternalXAxisRenderProp.tsx

BUDE-811: Tweak spacing with inputs and graph padding

---

src/components/LoadingIndicator/LoadingIndicator.less
src/components/LoadingIndicator/LoadingIndicator.tsx
src/components/LoadingIndicator/__snapshots__/LoadingIndicator.spec.jsx.snap
src/components/OverlayWrapper/OverlayWrapper.less
src/components/OverlayWrapper/OverlayWrapper.tsx

BUDE-479: Fix scroll locked content

---

CHANGELOG.md
src/components/DraggableLineChart/DraggableLineChart.less
src/components/DraggableLineChart/DraggableLineChart.tsx
src/components/DraggableLineChart/DraggableLineChartD3.ts
src/components/DraggableLineChart/examples/03.ExampleWithNoDataWithPreselect.tsx
src/components/DraggableLineChart/examples/04.ExampleWithNoDataWithoutPreselect.tsx

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/BUDE-858)

BUDE-858: Adding preselect area

---

CHANGELOG.md
src/components/VerticalListMenu/VerticalListMenu.tsx

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/verticallistmenu-less-fix/?path=/docs/navigation-verticallistmenu--basic)

VerticalListMenu less fix binding

---

.storybook/config.js
src/styles/master.less

Fixing the background image for Anx-react lib

---

package.json
tsconfig.json
tsconfig.publish.json

Fixed typescript build

---

src/components/DraggableLineChart/DraggableLineChart.tsx
src/components/DraggableLineChart/DraggableLineChartD3.ts
src/components/DraggableLineChart/examples/05.ExampleWithYAxisFormatter.tsx

BUDE-1150 : Adding YAxisTickFormatter as a prop.

---

src/components/ButtonGroup/__snapshots__/ButtonGroup.spec.tsx.snap
src/components/SearchableSelect/__snapshots__/SearchableSelect.spec.tsx.snap
src/components/SingleSelect/__snapshots__/SingleSelect.spec.tsx.snap

Fix: Updated snapshots

---

src/components/Axis/Axis.stories.tsx
src/components/AxisLabel/AxisLabel.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/Bar/Bar.stories.tsx
src/components/BarChart/BarChart.stories.tsx
src/components/Bars/Bars.stories.tsx
src/components/DraggableLineChart/DraggableLineChart.stories.tsx
src/components/ExampleComponent/ExampleComponent.stories.tsx
src/components/Icon/DangerLightIcon/DangerLightIcon.stories.tsx
src/components/Icon/Icon.stories.tsx
src/components/Icon/InfoLightIcon/InfoLightIcon.stories.tsx
src/components/Icon/SeparatorIcon/SeparatorIcon.stories.tsx
src/components/Icon/WarningLightIcon/WarningLightIcon.stories.tsx
src/components/Legend/Legend.stories.tsx
src/components/Line/Line.stories.tsx
src/components/LineChart/LineChart.stories.tsx
src/components/Lines/Lines.stories.tsx
src/components/PieChart/PieChart.stories.tsx
src/components/Point/Point.stories.tsx
src/components/Points/Points.stories.tsx
src/components/Table/Table.stories.tsx

fix categories

---

src/components/Banner/Banner.stories.tsx
src/components/Banner/Banner.tsx
src/util/component-types.ts

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/fix-banner-propTypes)
https://docspot.adnxs.net/projects/lucid/fix-banner-propTypes

give Banner propTypes

---

.storybook/preview.ts

Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/fix-lucid-fonts)
https://docspot.adnxs.net/projects/lucid/fix-lucid-fonts

Add master.less styles back to Storybook

---

src/components/Autocomplete/Autocomplete.less
src/components/Button/Button.less
src/components/DateSelect/__snapshots__/DateSelect.spec.tsx.snap
src/components/Legend/Legend.less
src/components/SearchField/SearchField.less
src/components/SearchableMultiSelect/SearchableMultiSelect.less
src/components/SearchableSelect/SearchableSelect.less
src/components/SearchableSingleSelect/SearchableSingleSelect.less
src/components/Selection/Selection.less
src/components/Sidebar/Sidebar.less
src/components/SingleSelect/SingleSelect.less
src/components/Submarine/Submarine.less
src/components/Switch/Switch.less
src/components/Table/Table.less
src/components/Tag/Tag.less
src/components/TextField/TextField.less
src/styles/variables.less

Storybook can be viewed:
SearchField:
https://docspot.adnxs.net/projects/lucid/CXP-2457-Fix-SearchField-Rounded-Corners/?path=/docs/controls-searchfield--default
SearchableSingleSelect:
https://docspot.adnxs.net/projects/lucid/CXP-2457-Fix-SearchField-Rounded-Corners/?path=/docs/controls-searchablesingleselect--default
SearchableMultiSelect:
https://docspot.adnxs.net/projects/lucid/CXP-2457-Fix-SearchField-Rounded-Corners/?path=/docs/controls-searchablemultiselect--default

Cxp 2457 fix search field rounded corners

---

src/components/Autocomplete/Autocomplete.less
src/components/Button/Button.less
src/components/DateSelect/__snapshots__/DateSelect.spec.tsx.snap
src/components/Legend/Legend.less
src/components/SearchField/SearchField.less
src/components/SearchableMultiSelect/SearchableMultiSelect.less
src/components/SearchableSelect/SearchableSelect.less
src/components/SearchableSingleSelect/SearchableSingleSelect.less
src/components/Selection/Selection.less
src/components/Sidebar/Sidebar.less
src/components/SingleSelect/SingleSelect.less
src/components/Submarine/Submarine.less
src/components/Switch/Switch.less
src/components/Table/Table.less
src/components/Tag/Tag.less
src/components/TextField/TextField.less
src/styles/variables.less

Storybook can be viewed:
https://docspot.adnxs.net/projects/lucid/CXP-Bump-Less-Less-Loader/?path=/docs/documentation-intro--page

Cxp bump less less loader

---

src/components/Accordion/Accordion.tsx
src/components/SearchableMultiSelect/SearchableMultiSelect.stories.tsx
src/components/SearchableMultiSelect/SearchableMultiSelect.tsx
src/components/SearchableMultiSelect/__snapshots__/SearchableMultiSelect.spec.tsx.snap

Storybook can be viewed 
https://docspot.adnxs.net/projects/lucid/BMAT-860-SearchableMultiSelect/?path=/docs/controls-searchablemultiselect--default

Bmat 860 searchable multi select

---

src/components/Badge/Badge.tsx
src/components/Bar/Bar.stories.tsx
src/components/Bar/Bar.tsx
src/components/DraggableList/DraggableList.stories.tsx
src/components/DraggableList/DraggableList.tsx
src/components/EmptyStateWrapper/EmptyStateWrapper.tsx
src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx
src/components/Line/Line.stories.tsx
src/components/Line/Line.tsx
src/components/Lines/Lines.stories.tsx
src/components/Lines/Lines.tsx
src/components/Panel/Panel.stories.tsx
src/components/Panel/Panel.tsx

Cxp 2482 fix omit props fc

---

src/components/DraggableLineChart/DraggableLineChart.tsx
src/components/Icon/Icon.tsx
src/components/Selection/Selection.stories.tsx
src/components/Selection/Selection.tsx
src/components/Selection/__snapshots__/Selection.spec.tsx.snap
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.tsx
src/components/TextFieldValidated/__snapshots__/TextFieldValidated.spec.tsx.snap
src/components/Typography/Typography.stories.tsx
src/components/Typography/Typography.tsx
src/components/Typography/__snapshots__/Typography.spec.tsx.snap
src/components/Underline/Underline.stories.tsx
src/components/Underline/Underline.tsx
src/components/Validation/Validation.stories.tsx
src/components/Validation/Validation.tsx
src/components/Validation/__snapshots__/Validation.spec.tsx.snap

Cxp 2488 fix omit props for five components

---

src/components/Switch/Switch.stories.tsx
src/components/Switch/__snapshots__/Switch.spec.tsx.snap
src/components/SwitchLabeled/SwitchLabeled.stories.tsx
src/components/SwitchLabeled/SwitchLabeled.tsx
src/components/SwitchLabeled/__snapshots__/SwitchLabeled.spec.tsx.snap

Update the stories for Switch and Switch labeled to Storybook 6
Storybook can be viewed [here](https://docspot.adnxs.net/projects/lucid/improvement_CXP-1767-update-switches-sb6)

Improvement/cxp 1767 update switches Storybook 6

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

update Contributing doc and PR Template

---

src/components/Grid/Grid.spec.tsx
src/components/Grid/Grid.stories.tsx
src/components/Grid/Grid.tsx

for the `Grid` component:
- Replace omitProps with specific list of pros, 
- update Stories to SB6
- add unit tests
https://docspot.adnxs.net/projects/lucid/CXP-2566-Grid-Replace-omitProps/?path=/docs/layout-grid--grid-columns

For Grid : Replace omitProps with specific list of pros, update Stories and add unit tests

---

src/components/SearchField/SearchField.tsx

CXP-3019: Remove optional chaining usage
